/**
 * CLI playbooks derived from AgenticFlow skill references.
 */

export interface Playbook {
  topic: string;
  title: string;
  summary: string;
  content: string;
}

export const PLAYBOOKS: Record<string, Playbook> = {
  "first-touch": {
    topic: "first-touch",
    title: "First Touch — AI Agent Onboarding",
    summary: "The ONE command every AI agent should run first. Returns auth, agents, models, blueprints, and what's new.",
    content: [
      "## STEP 1: Bootstrap (run this FIRST — it returns everything you need)",
      "```bash",
      "af bootstrap --json",
      "```",
      "This single command returns:",
      "- `auth` — are you authenticated? what workspace/project?",
      "- `agents` — your first 10 agents with id/name/model",
      "- `models` — available LLM models (Gemma 4, Gemini, GPT, DeepSeek, etc.)",
      "- `schemas` — 7 resource schemas for payload construction",
      "- `blueprints` — 6 ready-made company templates",
      "- `playbooks` — 12 guided execution paths",
      "- `whats_new` — latest features and AI-specific tips",
      "- `commands` — quick-reference for common operations",
      "",
      "VERIFY: `auth.authenticated === true` and `auth.health === true`.",
      "IF auth fails: run `af login` or set `AGENTICFLOW_API_KEY` env var.",
      "",
      "## STEP 2: Decide what to do",
      "",
      "**Talk to an existing agent:**",
      "```bash",
      "af agent run --agent-id <id from bootstrap> --message \"Hello\" --json",
      "```",
      "",
      "**Create a new agent:**",
      "```bash",
      "af agent scaffold --json                    # Generate valid payload",
      "af agent create --body <payload> --dry-run   # Validate",
      "af agent create --body <payload> --json       # Create",
      "```",
      "",
      "**Deploy a team to AgenticFlow (native, v1.6+):**",
      "```bash",
      "# The 6 blueprints are already in `af bootstrap --json > blueprints[]` — no separate",
      "# 'list' call needed. You can also see them in the tables below under `## Blueprints`.",
      "af workforce init --blueprint <id> --name \"My Team\" --dry-run --json  # Preview",
      "af workforce init --blueprint <id> --name \"My Team\" --json             # Creates",
      "                                                                       # workforce + N",
      "                                                                       # agents + wired",
      "                                                                       # graph, all in",
      "                                                                       # one command.",
      "af workforce publish --workforce-id <id> --json              # Mint public URL",
      "```",
      "",
      "## Choosing: single agent vs. workforce",
      "- **Single agent** (`af agent create`) — one chat endpoint, one assistant, prompt-based",
      "  routing inside one agent. Pick this for a customer-facing bot, a single task assistant,",
      "  a prompt experiment. Iterate with `af agent update --patch`.",
      "- **Workforce** (`af workforce init --blueprint <id>`) — multiple agents that hand off to",
      "  each other (trigger → coordinator → worker agents → output). Pick this when you need",
      "  orchestration: research-then-write pipelines, triage-then-specialist flows, the 6",
      "  built-in blueprints (dev-shop, marketing-agency, amazon-seller, etc).",
      "",
      "**Deploy to Paperclip (DEPRECATED — sunset 2026-10-14):**",
      "See `af playbook migrate-from-paperclip` for the full migration map.",
      "```bash",
      "af paperclip init --blueprint <id> --json   # Still works but prints deprecation warning",
      "```",
      "",
      "**See what's new after an upgrade:**",
      "```bash",
      "af changelog --json",
      "```",
      "",
      "## RULES FOR AI AGENTS",
      "1. Always use `--json` for machine-readable output",
      "2. Always use `--fields` on list commands to save context window",
      "3. Always use `--dry-run` before create commands",
      "4. Use `af schema <resource> --json` before constructing payloads",
      "5. Use `af agent run` (not `af agent stream`) for tool-call responses",
      "6. Errors return `{ schema: \"agenticflow.error.v1\", code, message, hint }`",
      "",
      "## PROACTIVE: Tell your owner what you can do",
      "After bootstrap, inform your owner:",
      "- How many agents they have and what models they use",
      "- Available blueprints for one-command company deployment",
      "- New features from `whats_new` (e.g. Gemma 4, amazon-seller pack)",
      "- Suggest: \"Want me to set up an AI team for your business?\"",
    ].join("\n"),
  },
  "template-bootstrap": {
    topic: "template-bootstrap",
    title: "Bootstrap From Templates",
    summary: "Fetch template samples locally so cold agents can compose workflows, agents, and workforces with less trial-and-error.",
    content: [
      "Template bootstrap flow",
      "1. Sync templates into local cache:",
      "   `agenticflow templates sync --limit 100 --json`",
      "2. Inspect local cache summary:",
      "   `agenticflow templates index --json`",
      "3. Read generated files in `.agenticflow/templates`:",
      "   - `manifest.json` (counts, source operations, sync issues)",
      "   - `workflow_templates.json`, `agent_templates.json`, `workforce_templates.json`",
      "   - `workflow/`, `agent/`, `workforce/` per-template files",
      "4. Duplicate templates directly (web-like flow):",
      "   `agenticflow templates duplicate workflow --template-id <workflow_template_id> --json`",
      "   `agenticflow templates duplicate agent --template-id <agent_template_id> --json`",
      "   `agenticflow templates duplicate agent --template-file <local_agent_template.json> --cache-dir .agenticflow/templates --dry-run --json`",
      "5. Build custom assets by adapting nearest templates, then validate:",
      "   `agenticflow workflow validate --body @workflow.json --local-only`",
      "   `agenticflow agent create --body @agent.json`",
      "6. If templates do not cover your use case, continue with docs:",
      "   `https://docs.agenticflow.ai/`",
      "   `https://docs.agenticflow.ai/~gitbook/mcp`",
      "",
      "Notes",
      "- `workforce` template source may require `--workforce-id <id>` on some backends.",
      "- `templates duplicate agent` duplicates referenced workflow templates first.",
      "- Use `--cache-dir .agenticflow/templates` to resolve workflow templates locally before API fetch.",
      "- Use `--strict` during sync when CI must fail on partial fetch.",
    ].join("\n"),
  },
  "workflow-build": {
    topic: "workflow-build",
    title: "Build Workflows",
    summary: "Design a linear node pipeline and publish it with CLI commands.",
    content: [
      "Workflow design checklist",
      "1. Define `input_schema` first.",
      "2. Discover node types: `agenticflow node-types list` or `agenticflow node-types search --query llm`.",
      "3. Inspect node requirements: `agenticflow node-types get --name <node_type>`.",
      "4. Fetch dynamic dropdown values when needed:",
      "   `agenticflow node-types dynamic-options --name <node_type> --field-name <field>`.",
      "5. Create workflow JSON body with required fields:",
      "   `name`, `project_id`, `nodes`, `output_mapping`, `input_schema`.",
      "6. Create workflow:",
      "   `agenticflow workflow create --workspace-id <workspace_id> --body @workflow.json`.",
      "7. Update workflow:",
      "   `agenticflow workflow update --workspace-id <workspace_id> --workflow-id <workflow_id> --body @workflow.json`.",
      "",
      "Notes",
      "- Prefer node types that do not require connections when possible.",
      "- Workflows execute sequentially top-to-bottom.",
      "- Use `{{...}}` references to map outputs from prior nodes.",
    ].join("\n"),
  },
  "workflow-run": {
    topic: "workflow-run",
    title: "Run Workflows",
    summary: "Execute a workflow and monitor the workflow run lifecycle.",
    content: [
      "Run checklist",
      "1. Start run:",
      "   `agenticflow workflow run --workflow-id <workflow_id> --input @input.json`.",
      "2. Poll status:",
      "   `agenticflow workflow run-status --workflow-run-id <workflow_run_id>`.",
      "3. Inspect result fields:",
      "   `status`, `output`, `state.nodes_state`, `state.error`.",
      "",
      "Tips",
      "- Keep polling until status is `success` or `failed`.",
      "- Validate workflow payloads before create/update:",
      "  `agenticflow workflow validate --body @workflow.json`.",
    ].join("\n"),
  },
  "agent-build": {
    topic: "agent-build",
    title: "Build Agents",
    summary: "Create and operate agents with tool configs and stream calls.",
    content: [
      "Agent checklist",
      "1. Prepare create payload with required fields:",
      "   `name`, `tools`, `project_id`.",
      "2. Create agent:",
      "   `agenticflow agent create --body @agent.json`.",
      "3. Read/update agent:",
      "   `agenticflow agent get --agent-id <agent_id>`",
      "   `agenticflow agent update --agent-id <agent_id> --body @agent-update.json`.",
      "4. Interact through streaming endpoint:",
      "   `agenticflow agent stream --agent-id <agent_id> --body @stream-body.json`.",
      "",
      "Best practices",
      "- Keep tool sets minimal and focused.",
      "- Use explicit system prompts and response formats.",
      "- Test with short stream prompts before production traffic.",
    ].join("\n"),
  },
  "quickstart": {
    topic: "quickstart",
    title: "Quickstart: Zero to Working Agent in 5 Minutes",
    summary: "Executable onboarding for AI agents and humans. Run these commands in order — every step has verification.",
    content: [
      "## STEP 1: Verify auth (run this FIRST)",
      "```bash",
      "af doctor --json --strict",
      "```",
      "VERIFY: output has `\"health\": true`. If false, run `af login` to authenticate.",
      "EXTRACT: `projectId` value — you need it for Step 3.",
      "",
      "## STEP 2: List available agents",
      "```bash",
      "af agent list --fields id,name,model --json",
      "```",
      "VERIFY: returns a JSON array. If empty, proceed to Step 3 to create one.",
      "IF NOT EMPTY: skip Step 3, use the first agent's `id` for Step 4.",
      "",
      "## STEP 3: Create an agent (only if Step 2 returned empty)",
      "Get schema first:",
      "```bash",
      "af schema agent --json",
      "```",
      "Then create:",
      "```bash",
      "af agent create --body '{\"name\": \"My Assistant\", \"tools\": [], \"project_id\": \"PROJECT_ID_FROM_STEP_1\"}' --dry-run --json",
      "```",
      "VERIFY: `valid: true`. Then create for real (remove --dry-run):",
      "```bash",
      "af agent create --body '{\"name\": \"My Assistant\", \"tools\": [], \"project_id\": \"PROJECT_ID_FROM_STEP_1\"}' --json",
      "```",
      "EXTRACT: `id` from response.",
      "",
      "## STEP 4: Send a task to the agent",
      "```bash",
      "af agent run --agent-id AGENT_ID --message \"Hello, what can you do?\" --json",
      "```",
      "VERIFY: response has `status: \"completed\"` and non-empty `response` field.",
      "EXTRACT: `thread_id` for follow-up conversations.",
      "",
      "## STEP 5: Follow up (uses same thread)",
      "```bash",
      "af agent run --agent-id AGENT_ID --message \"Tell me more\" --thread-id THREAD_ID_FROM_STEP_4 --json",
      "```",
      "VERIFY: agent remembers context from Step 4.",
      "",
      "## DECISION TREE: What next?",
      "- Deploy agents to run on Paperclip → `af playbook company-from-scratch`",
      "- Receive tasks from Linear/webhooks → `af playbook gateway-setup`",
      "- Browse marketplace templates → `af templates sync --limit 50 --json`",
      "- Learn payload formats → `af schema agent --json`",
      "",
      "## ERROR HANDLING",
      "All errors return: `{ schema: \"agenticflow.error.v1\", code, message, hint }`",
      "- `health: false` → run `af login` to set API key",
      "- `local_schema_validation_failed` → check payload against `af schema <resource> --json`",
      "- `request_failed` → check the `message` field for API error details",
    ].join("\n"),
  },
  "gateway-setup": {
    topic: "gateway-setup",
    title: "Gateway: Receive Tasks From Any Platform",
    summary: "Set up the webhook gateway to receive tasks from Paperclip, Linear, GitHub, or any custom webhook and route them to AgenticFlow agents.",
    content: [
      "The gateway is a webhook server that translates external platform events",
      "into AgenticFlow agent calls. It supports multiple channels simultaneously.",
      "",
      "## Concept: Channels",
      "A channel is any platform that sends tasks to your agents:",
      "- **paperclip** — Paperclip heartbeat webhooks (task management for AI companies)",
      "- **linear** — Linear issue/comment webhooks (engineering project management)",
      "- **webhook** — Generic JSON POST (any system, any automation)",
      "",
      "List available channels:",
      "```",
      "af gateway channels",
      "```",
      "",
      "## Quick Start: Generic Webhook (No Setup Required)",
      "```",
      "af gateway serve --channels webhook --verbose",
      "```",
      "Now send a task from anywhere:",
      "```",
      "curl -X POST http://localhost:4100/webhook/webhook \\",
      '  -H "Content-Type: application/json" \\',
      '  -d \'{"agent_id": "<AF_AGENT_ID>", "message": "Summarize the Q4 report"}\'',
      "```",
      "The agent processes the task and returns the result in the HTTP response.",
      "",
      "With a callback URL, results are also POSTed back:",
      "```",
      "curl -X POST http://localhost:4100/webhook/webhook \\",
      '  -H "Content-Type: application/json" \\',
      '  -d \'{"agent_id": "<ID>", "message": "Do X", "callback_url": "https://your-app.com/results"}\'',
      "```",
      "",
      "## Paperclip Channel",
      "Receive tasks from a Paperclip company:",
      "```",
      "af gateway serve --channels paperclip --paperclip-url http://localhost:3100 --verbose",
      "```",
      "Then configure Paperclip agents with `adapterConfig.url = http://localhost:4100/webhook/paperclip`.",
      "Or use the shortcut: `af paperclip connect` (updates all deployed agents).",
      "",
      "Full Paperclip workflow: see `af playbook deploy-to-paperclip`.",
      "",
      "## Linear Channel",
      "Receive tasks from Linear issues:",
      "```",
      "export LINEAR_API_KEY=lin_api_xxxxx",
      'export LINEAR_AGENT_MAP=\'{"ENG": "<af-agent-id>", "DES": "<af-agent-id>"}\'',
      "af gateway serve --channels linear --verbose",
      "```",
      "Then in Linear: Settings > API > Webhooks > add URL:",
      "  `https://your-gateway-url/webhook/linear`",
      "  Events: Issues (created, updated), Comments (created)",
      "",
      "The gateway maps Linear teams to AF agents via LINEAR_AGENT_MAP.",
      "When an issue is created in team ENG, the mapped agent processes it.",
      "Agent responses are posted back as Linear comments.",
      "",
      "## Multiple Channels Simultaneously",
      "```",
      "af gateway serve --channels paperclip,linear,webhook --verbose",
      "```",
      "Each channel gets its own webhook endpoint:",
      "- POST /webhook/paperclip",
      "- POST /webhook/linear",
      "- POST /webhook/webhook",
      "- GET /health (lists active channels)",
      "",
      "## Serverless Deployment",
      "The gateway exports a standard Request -> Response handler.",
      "Import `createGatewayHandler` from the SDK for Vercel, Lambda, etc:",
      "```typescript",
      "import { createGatewayHandler } from '@pixelml/agenticflow-cli/gateway/server';",
      "import { WebhookConnector } from '@pixelml/agenticflow-cli/gateway/connectors';",
      "const handler = createGatewayHandler(config, [new WebhookConnector()]);",
      "export default handler; // Vercel / Cloudflare Workers",
      "```",
      "No always-running server required.",
      "",
      "## For AI Agents Reading This",
      "1. Start with `af gateway serve --channels webhook` for the simplest setup.",
      "2. Use `af gateway channels` to see available connectors.",
      "3. The generic webhook accepts: `{ agent_id, message, task_id?, callback_url? }`.",
      "4. Health check: `GET /health` returns `{ connectors: [...] }`.",
      "5. To add a new channel, implement the ChannelConnector interface.",
    ].join("\n"),
  },
  "deploy-to-paperclip": {
    topic: "deploy-to-paperclip",
    title: "Deploy Agents to Paperclip (DEPRECATED)",
    summary: "[DEPRECATED — sunset 2026-10-14] Publish AgenticFlow agents to a Paperclip company. Use `af playbook migrate-from-paperclip` for the AgenticFlow-native alternative.",
    content: [
      "# ⚠️  DEPRECATED — Migrate to `af workforce` by 2026-10-14",
      "",
      "This playbook describes the legacy Paperclip-based deploy. As of CLI v1.5.0,",
      "AgenticFlow ships a native multi-agent deploy surface (`af workforce *`) that",
      "replaces most of this flow — no separate Paperclip instance, no gateway to run,",
      "no connect step. See:",
      "",
      "- **`af playbook migrate-from-paperclip`** — command-by-command map",
      "- **`af playbook amazon-seller`** or **`af playbook company-from-scratch`** — native examples",
      "- **`af workforce init --blueprint <id> --json`** — one-command native deploy (v1.6+)",
      "",
      "The commands below still work — you'll see a one-time `[deprecated]` warning per session.",
      "Silence with `AF_SILENCE_DEPRECATIONS=1`. After the 2026-10-14 sunset the `af paperclip *`",
      "commands will be removed.",
      "",
      "---",
      "",
      "Paperclip is an orchestration control plane for AI agent companies.",
      "AgenticFlow agents can be deployed to Paperclip as HTTP-adapter workers",
      "that receive tasks and execute them.",
      "",
      "## Prerequisites",
      "- AgenticFlow CLI authenticated (`af login` or `af doctor`)",
      "- At least one agent in AgenticFlow (`af agent list`)",
      "- A running Paperclip instance (default: http://localhost:3100)",
      "",
      "## Step 1: Create a Company",
      "```",
      'af paperclip company create --name "My AI Company" --budget 100000',
      "```",
      "Budget is in cents (100000 = $1,000/month).",
      "",
      "## Step 2: Deploy Agents",
      "Deploy an AgenticFlow agent to Paperclip:",
      "```",
      "af paperclip deploy --agent-id <AF_AGENT_ID> --role engineer",
      "```",
      "Available roles: ceo, cto, cmo, cfo, engineer, designer, pm, qa, devops, researcher, general.",
      "",
      "Deploy multiple agents to build a team:",
      "```",
      "af paperclip deploy --agent-id <ID1> --role engineer",
      "af paperclip deploy --agent-id <ID2> --role cmo",
      "af paperclip deploy --agent-id <ID3> --role designer",
      "```",
      "",
      "## Step 3: Set Goals and Create Tasks",
      "```",
      'af paperclip goal create --title "Launch the product by Q2" --level company --status active',
      "```",
      "```",
      'af paperclip issue create --title "Build landing page" --assignee <PC_AGENT_ID> --priority high',
      "```",
      "",
      "## Step 4: Start the Gateway",
      "```",
      "af gateway serve --channels paperclip --verbose",
      "```",
      "",
      "## Step 5: Connect Agents to the Gateway",
      "```",
      "af paperclip connect",
      "```",
      "This updates all deployed agents to route heartbeats through the gateway.",
      "",
      "## Step 6: Trigger Work",
      "```",
      'af paperclip agent wakeup --id <PC_AGENT_ID> --reason "Work on your tasks"',
      "```",
      "The gateway fetches the agent's assigned issue from Paperclip,",
      "sends the full task context to the AgenticFlow agent, and posts",
      "the agent's response back as a comment on the issue.",
      "",
      "## Step 7: Monitor",
      "```",
      "af paperclip dashboard",
      "af paperclip issue list",
      "af paperclip issue comments --id <ISSUE_ID>",
      "```",
      "",
      "## Full Command Reference",
      "```",
      "af paperclip company list|get|create|update|archive|delete",
      "af paperclip agent list|get|update|pause|resume|terminate|wakeup|delete",
      "af paperclip goal list|get|create|update|delete",
      "af paperclip issue list|get|create|update|assign|comment|comments|delete",
      "af paperclip approval list|approve|reject",
      "af paperclip dashboard",
      "af paperclip deploy --agent-id <id>",
      "af paperclip connect",
      "```",
      "",
      "## Environment Variables",
      "```",
      "PAPERCLIP_URL=http://localhost:3100   # Paperclip instance URL",
      "PAPERCLIP_COMPANY_ID=<uuid>           # Default company (auto-detected if only one)",
      "```",
      "",
      "## For AI Agents Reading This",
      "1. Run `af agent list --json` to find available AgenticFlow agents.",
      "2. Run `af paperclip company create --name <name>` to set up a company.",
      "3. Use `af paperclip deploy --agent-id <id> --role <role>` for each agent.",
      "4. Start the gateway: `af gateway serve --channels paperclip`.",
      "5. Connect agents: `af paperclip connect`.",
      "6. Create goals and issues, then trigger heartbeats.",
      "7. Check results with `af paperclip issue comments --id <id>`.",
      "8. Company ID auto-resolves when only one company exists.",
    ].join("\n"),
  },
  "agent-channels": {
    topic: "agent-channels",
    title: "Connect Agents to External Channels",
    summary: "Route work to AgenticFlow agents from Linear, Paperclip, GitHub, Slack, or any webhook — using the gateway as a universal adapter.",
    content: [
      "AgenticFlow agents can receive work from any platform via the gateway.",
      "This playbook shows how to wire up each supported channel.",
      "",
      "## Architecture",
      "```",
      "External Platform  →  POST /webhook/<channel>  →  Gateway  →  AF Agent  →  Result back to platform",
      "```",
      "",
      "## Channel 1: Generic Webhook (simplest)",
      "Any system that can make HTTP requests can send tasks:",
      "```",
      "af gateway serve --channels webhook",
      "```",
      "Send a task:",
      "```json",
      "{",
      '  "agent_id": "<AF_AGENT_ID>",',
      '  "message": "Analyze this data and provide insights",',
      '  "task_id": "TASK-001",',
      '  "callback_url": "https://my-app.com/webhook/results"',
      "}",
      "```",
      "POST to: `http://gateway:4100/webhook/webhook`",
      "",
      "Use cases: Zapier, Make, n8n, custom apps, cron jobs, Slack bots, CI/CD.",
      "",
      "## Channel 2: Paperclip",
      "Full AI company orchestration with goals, tasks, budgets:",
      "```",
      "af gateway serve --channels paperclip --paperclip-url http://localhost:3100",
      "af paperclip deploy --agent-id <id>",
      "af paperclip connect",
      "```",
      "See `af playbook deploy-to-paperclip` for the full guide.",
      "",
      "## Channel 3: Linear",
      "Engineering project management — agents process Linear issues:",
      "```",
      "export LINEAR_API_KEY=lin_api_xxxxx",
      'export LINEAR_AGENT_MAP=\'{"ENG": "<af-agent-id>", "DESIGN": "<af-agent-id>"}\'',
      "af gateway serve --channels linear",
      "```",
      "In Linear: Settings > API > Webhooks > add `https://your-url/webhook/linear`",
      "",
      "How it works:",
      "- Issue created in ENG team → mapped AF agent receives full issue context",
      "- Comment added to issue → agent processes the comment",
      "- Agent response posted back as a Linear comment",
      "",
      "## Running Multiple Channels",
      "```",
      "af gateway serve --channels paperclip,linear,webhook --verbose",
      "```",
      "Each channel gets its own endpoint. One gateway handles all platforms.",
      "",
      "## Adding a New Channel",
      "Implement the ChannelConnector interface (2 methods):",
      "```typescript",
      "interface ChannelConnector {",
      "  name: string;",
      "  parseWebhook(headers, body): Promise<NormalizedTask | null>;",
      "  postResult(task, resultText): Promise<void>;",
      "}",
      "```",
      "parseWebhook: extract task info from the platform's webhook payload.",
      "postResult: post the agent's response back to the platform.",
      "",
      "## For AI Agents Reading This",
      "1. The simplest channel is `webhook` — just POST `{ agent_id, message }`.",
      "2. For Paperclip: use `af paperclip deploy` + `af paperclip connect`.",
      "3. For Linear: set LINEAR_API_KEY and LINEAR_AGENT_MAP, add webhook in Linear UI.",
      "4. Multiple channels can run simultaneously on one gateway.",
      "5. Health check: `GET /health` shows active channels.",
      "6. All channels normalize to NormalizedTask before calling AF agent.",
    ].join("\n"),
  },
  "company-from-scratch": {
    topic: "company-from-scratch",
    title: "Create an AI Company from Scratch",
    summary: "Executable playbook: an AI agent can run these commands in order to create a complete Paperclip company powered by AgenticFlow agents.",
    content: [
      "## PREREQUISITES — run these first, stop if any fail",
      "```bash",
      "af doctor --json --strict",
      "```",
      "VERIFY: `health: true`. EXTRACT: `projectId`.",
      "",
      "```bash",
      "af agent list --fields id,name,model --json",
      "```",
      "VERIFY: at least 1 agent exists in the workspace (not strictly required — `af workforce init` creates fresh ones). If you want to re-use existing agents, note their IDs.",
      "",
      "---",
      "",
      "## OPTION A: AgenticFlow-native workforce (RECOMMENDED, v1.6+)",
      "",
      "One command creates workforce + N agents + wired DAG. No Paperclip, no gateway, no webhooks.",
      "",
      "### A1. Choose a blueprint",
      "```bash",
      "af paperclip blueprints --json",
      "```",
      "Returns: array of `{ id, name, description, agents }`. Pick one based on the user's goal:",
      "- `dev-shop` — build software (CEO, engineer, designer, QA)",
      "- `marketing-agency` — marketing campaigns (director, content, designer, researcher)",
      "- `sales-team` — lead gen + outreach (director, researcher, SDR)",
      "- `content-studio` — content production (creative dir, social, writer, visual)",
      "- `support-center` — customer support (manager, agent, KB)",
      "- `amazon-seller` — Amazon SG seller team (CEO, listing, PPC, research, support)",
      "",
      "### A2. Deploy the team",
      "```bash",
      "af workforce init --blueprint BLUEPRINT_ID --name \"My Team\" --dry-run --json     # preview",
      "af workforce init --blueprint BLUEPRINT_ID --name \"My Team\" --json              # creates",
      "```",
      "VERIFY: response has `schema: \"agenticflow.workforce.init.v1\"`, `mode: \"full\"`, `skeleton: false`, non-empty `agents` array.",
      "EXTRACT: `workforce_id`, each `agents[].agent_id`.",
      "",
      "### A3. Inspect the wired graph (optional)",
      "```bash",
      "af workforce schema --workforce-id <id> --json",
      "af workforce validate --workforce-id <id> --json  # expects 0 errors",
      "```",
      "",
      "### A4. Attach tools/MCPs per agent (recommended)",
      "Each agent starts with `tools: []`. For real use, attach Composio MCP clients (see `af playbook mcp-client-quirks`):",
      "```bash",
      "af mcp-clients list --name-contains \"google\" --fields id,name --json",
      "af mcp-clients inspect --id <mcp_id> --json",
      "af agent update --agent-id <agent_id> --patch --body '{\"mcp_clients\":[{\"mcp_client_id\":\"<id>\",\"run_behavior\":\"auto_run\",\"tools\":{}}]}' --json",
      "```",
      "",
      "### A5. Run it",
      "```bash",
      "af workforce run --workforce-id <id> --trigger-data '{\"message\":\"Kick off week 1 tasks\"}'",
      "af workforce publish --workforce-id <id> --json  # public URL for teammates",
      "```",
      "",
      "## OPTION A-LEGACY: Paperclip (DEPRECATED — sunset 2026-10-14)",
      "",
      "Still functional but emits a deprecation warning. See `af playbook migrate-from-paperclip`.",
      "",
      "```bash",
      "af paperclip init --blueprint BLUEPRINT_ID --budget 50000 --json",
      "```",
      "VERIFY: response has `schema: \"agenticflow.paperclip.init.v1\"`, non-empty `agents` and `tasks` arrays.",
      "EXTRACT: `company.id`, each agent's `pcAgent` ID, each task identifier.",
      "",
      "### A3. Start gateway (run in background or separate terminal)",
      "```bash",
      "af gateway serve --channels paperclip &",
      "```",
      "VERIFY: `curl -s http://localhost:4100/health` returns `status: \"ok\"`.",
      "",
      "### A4. Connect agents to gateway",
      "```bash",
      "af paperclip connect --json",
      "```",
      "VERIFY: every agent shows `status: \"connected\"`.",
      "",
      "### A5. Trigger an agent",
      "Pick any agent + task from A2 output:",
      "```bash",
      "curl -s -X POST http://localhost:4100/webhook/paperclip \\",
      "  -H \"Content-Type: application/json\" \\",
      "  -d '{\"agentId\":\"PC_AGENT_ID\",\"runId\":\"RANDOM_UUID\",\"context\":{\"issueId\":\"TASK_ID\",\"taskKey\":\"IDENTIFIER\",\"wakeReason\":\"Start working\",\"wakeSource\":\"on_demand\"}}'",
      "```",
      "VERIFY: `status: \"completed\"`, `response` field has agent's work output.",
      "",
      "### A6. Check results",
      "```bash",
      "af paperclip issue comments --id TASK_ID --json",
      "af paperclip dashboard --json",
      "```",
      "VERIFY: comment posted by agent, dashboard shows tasks + agents.",
      "",
      "---",
      "",
      "## OPTION B: Custom company (step by step)",
      "",
      "### B1. Create company",
      "```bash",
      "af paperclip company create --name \"COMPANY_NAME\" --budget BUDGET_CENTS --json",
      "```",
      "EXTRACT: `id` as COMPANY_ID.",
      "",
      "### B2. Deploy agents",
      "For each agent from prerequisites:",
      "```bash",
      "af paperclip deploy --agent-id AF_AGENT_ID --company-id COMPANY_ID --role ROLE --json",
      "```",
      "ROLES: ceo, cto, cmo, cfo, engineer, designer, pm, qa, devops, researcher, general",
      "EXTRACT: `paperclip.agent_id` as PC_AGENT_ID for each.",
      "",
      "### B3. Set goal",
      "```bash",
      "af paperclip goal create --company-id COMPANY_ID --title \"GOAL\" --level company --status active --json",
      "```",
      "EXTRACT: `id` as GOAL_ID.",
      "",
      "### B4. Create tasks",
      "```bash",
      "af paperclip issue create --company-id COMPANY_ID --title \"TASK\" --description \"DETAILS\" --assignee PC_AGENT_ID --goal-id GOAL_ID --priority high --json",
      "```",
      "EXTRACT: `id` as ISSUE_ID, `identifier` for display.",
      "",
      "### B5. Start gateway + connect (same as A3-A4)",
      "```bash",
      "af gateway serve --channels paperclip &",
      "af paperclip connect --company-id COMPANY_ID --json",
      "```",
      "",
      "### B6. Trigger + monitor (same as A5-A6)",
      "",
      "---",
      "",
      "## CONFIGURATION",
      "| Variable | Purpose | Default |",
      "|----------|---------|---------|",
      "| `PAPERCLIP_URL` | Paperclip instance URL | `http://localhost:3100` |",
      "| `PAPERCLIP_COMPANY_ID` | Auto-saved after create | (auto) |",
      "| `--heartbeat-interval` | Auto-trigger interval (0=manual only) | `0` |",
      "| `--budget` | Monthly budget in cents | `50000` |",
      "",
      "## ERROR RECOVERY",
      "- `paperclip_unreachable` → Paperclip is not running at PAPERCLIP_URL",
      "- `agent_fetch_failed` → AF agent ID doesn't exist. Run `af agent list --json`",
      "- `company_ambiguous` → Multiple companies. Use `--company-id` explicitly",
      "- Agent status `error` after heartbeat → gateway URL may be wrong. Run `af paperclip connect`",
    ].join("\n"),
  },
  "amazon-seller": {
    topic: "amazon-seller",
    title: "Amazon Seller AI Team",
    summary: "Deploy a 5-agent AI team for Amazon Singapore sellers — listing optimization, PPC, competitor analysis, pricing, and customer support. One command.",
    content: [
      "Deploy an AI team that runs your Amazon Singapore business 24/7.",
      "",
      "## PREREQUISITES",
      "```bash",
      "af doctor --json --strict",
      "```",
      "VERIFY: `health: true`. If not, run `af login`.",
      "",
      "## OPTION A: AgenticFlow-native (RECOMMENDED, v1.6+)",
      "",
      "One command creates workforce + 5 real agents + wired DAG graph (trigger → CEO coordinator → 4 workers → output).",
      "",
      "```bash",
      "af workforce init --blueprint amazon-seller --name \"My Amazon Team\" --include-optional-slots --dry-run --json",
      "# ^ Preview: see agent specs + estimated node/edge count, no side effects",
      "",
      "af workforce init --blueprint amazon-seller --name \"My Amazon Team\" --include-optional-slots --json",
      "# ^ Creates it for real. Response: { workforce_id, agents:[{slot_role, agent_id, title}],",
      "#                                    node_count, edge_count, next_steps }",
      "```",
      "",
      "VERIFY: response has `mode: \"full\"`, `agents` array with 4-5 entries (each with `agent_id`), and `skeleton: false`.",
      "",
      "### Confirm the graph is wired (optional)",
      "```bash",
      "af workforce schema --workforce-id <id> --json",
      "af workforce validate --workforce-id <id> --json    # 0 errors expected",
      "```",
      "",
      "### Attach tools/MCPs per agent (recommended for real use)",
      "Each auto-created agent starts with `tools: []`. To give them capabilities:",
      "```bash",
      "# Example — give the Listing & SEO Specialist (CMO role) Google Sheets for tracking",
      "af mcp-clients list --name-contains \"google sheets\" --fields id,name --json",
      "af mcp-clients inspect --id <sheets_mcp_id> --json   # classify Pipedream vs Composio",
      "af agent update --agent-id <cmo_agent_id> --patch --body '{\"mcp_clients\":[{\"mcp_client_id\":\"<id>\",\"run_behavior\":\"auto_run\",\"tools\":{}}]}' --json",
      "```",
      "",
      "See `af playbook mcp-client-quirks` for the Pipedream vs Composio write-safety distinction.",
      "",
      "### Run it",
      "```bash",
      "af workforce run --workforce-id <id> --trigger-data '{\"message\":\"Optimize our top 3 ASINs for CNY 2026.\"}'",
      "# Streams SSE events — each event prints one JSON line. Exits when stream closes.",
      "",
      "af workforce publish --workforce-id <id> --json  # Mint a public_key + public_url so teammates can hit it",
      "```",
      "",
      "## OPTION B: Paperclip (DEPRECATED — sunset 2026-10-14)",
      "",
      "Still works but emits a deprecation warning per session. Silence with `AF_SILENCE_DEPRECATIONS=1`.",
      "",
      "```bash",
      "af paperclip init --blueprint amazon-seller --budget 100000 --json",
      "af gateway serve --channels paperclip &",
      "af paperclip connect --json",
      "af paperclip issue list --json",
      "```",
      "",
      "See `af playbook migrate-from-paperclip` for the full paperclip → workforce command map.",
      "",
      "## WHAT THE 5 AGENTS DO",
      "- **Amazon Business Manager (CEO)** — strategy, P&L oversight, coordinates the team",
      "- **Listing & SEO Specialist (CMO)** — product listings, keyword research, A+ content",
      "- **PPC Campaign Manager (Engineer)** — Sponsored Products/Brands/Display, bid optimization",
      "- **Market & Competitor Analyst (Researcher)** — pricing intel, trend analysis",
      "- **Customer Support Agent (General, optional)** — buyer messages, review replies — only created if you pass `--include-optional-slots`",
      "",
      "## STARTER TASKS (embedded in trigger.meta.starter_tasks)",
      "1. **Optimize top 3 product listings** (CMO) — title, bullets, backend keywords for SG market",
      "2. **Set up PPC campaigns** (Engineer) — Sponsored Products, SGD 500/mo, 25% ACoS target",
      "3. **Competitive analysis report** (Researcher) — top 5 competitors, pricing, gaps",
      "4. **Draft review responses** (Support) — handle recent 1-2 star reviews (optional agent)",
      "5. **Q2 pricing strategy** (CEO) — 11.11, Great Singapore Sale, National Day promos",
      "",
      "## FOR AI AGENTS",
      "1. Default: `af workforce init --blueprint amazon-seller --name \"<name>\" --include-optional-slots --json` creates a runnable 5-agent team in one call.",
      "2. Attach MCPs/tools to each agent via `af agent update --patch` (tools start empty on init).",
      "3. Smoke test with `af workforce run --workforce-id <id> --trigger-data '{\"message\":\"...\"}'`.",
      "4. Publish a public URL via `af workforce publish --workforce-id <id>` when ready to hand off.",
      "5. Clean up test deploys with `af workforce delete --workforce-id <id>` + `af agent delete --agent-id <id>` for each created agent.",
    ].join("\n"),
  },
  "mcp-to-cli-map": {
    topic: "mcp-to-cli-map",
    title: "MCP To CLI Mapping",
    summary: "Replace common AgenticFlow MCP actions with native CLI commands.",
    content: [
      "MCP style -> CLI equivalent",
      "- `agenticflow_list_node_types` -> `agenticflow node-types list`",
      "- `agenticflow_search_node_types` -> `agenticflow node-types search --query <q>`",
      "- `agenticflow_get_node_type_details` -> `agenticflow node-types get --name <node_type>`",
      "- `agenticflow_get_dynamic_options` ->",
      "  `agenticflow node-types dynamic-options --name <node_type> --field-name <field>`",
      "- `agenticflow_create_workflow` ->",
      "  `agenticflow workflow create --workspace-id <workspace_id> --body @workflow.json`",
      "- `agenticflow_update_workflow` ->",
      "  `agenticflow workflow update --workspace-id <workspace_id> --workflow-id <workflow_id> --body @workflow.json`",
      "- `agenticflow_execute_workflow` ->",
      "  `agenticflow workflow run --workflow-id <workflow_id> --input @input.json`",
      "- `agenticflow_get_workflow_run` ->",
      "  `agenticflow workflow run-status --workflow-run-id <workflow_run_id>`",
      "- `agenticflow_list_app_connections` ->",
      "  `agenticflow connections list --workspace-id <workspace_id>`",
    ].join("\n"),
  },

  "migrate-from-paperclip": {
    topic: "migrate-from-paperclip",
    title: "Migrate from `af paperclip` to `af workforce`",
    summary:
      "Paperclip is deprecated. This playbook maps every `af paperclip *` command to its AgenticFlow-native equivalent under `af workforce *`.",
    content: [
      "## Why migrate",
      "",
      "`af paperclip *` deploys AI teams to a Paperclip instance (external orchestrator).",
      "`af workforce *` deploys them as AgenticFlow-native workforces — a DAG of agents",
      "that runs directly on the AgenticFlow platform with SSE streaming, versioning, and",
      "public-key embedding. One less moving part, one less instance to operate.",
      "",
      "Paperclip remains available through 2026-10-14 (6-month sunset). After that, the",
      "`af paperclip *` command group will be removed. You can silence the deprecation",
      "warnings today with `AF_SILENCE_DEPRECATIONS=1`, but prefer migrating.",
      "",
      "## Command-by-command map",
      "",
      "| Paperclip | AgenticFlow-native | Notes |",
      "|---|---|---|",
      "| `af paperclip blueprints` | `af paperclip blueprints` (still works) | Blueprint catalog is CLI-side; same 6 blueprints work for both targets |",
      "| `af paperclip init --blueprint <id>` | `af workforce init --blueprint <id>` | Creates a native workforce from the same blueprint |",
      "| `af paperclip deploy --agent-id <id>` | `af workforce create` + `af workforce deploy` | Attach the agent as a node in a workforce graph |",
      "| `af paperclip company list` | `af workforce list` | A company ≈ a workforce |",
      "| `af paperclip company get` | `af workforce get` | |",
      "| `af paperclip company create` | `af workforce create` | |",
      "| `af paperclip company update` | `af workforce update` (supports `--patch`) | |",
      "| `af paperclip company delete` | `af workforce delete` | |",
      "| `af paperclip agent list` (in company) | `af workforce schema --workforce-id <id>` | Returns nodes + edges; agents are nodes of type `agent` |",
      "| `af paperclip agent update` | Edit the graph + `af workforce deploy` | Use `PUT /schema` bulk replace |",
      "| `af paperclip issue list/create/assign` | — | Issues are Paperclip-specific. Workforce tasks live in trigger_data passed to `af workforce run` |",
      "| `af paperclip approval list/approve/reject` | — | Approvals are Paperclip-specific orchestration |",
      "| `af paperclip dashboard` | `af workforce list` + `af workforce versions list` | Combined overview |",
      "| `af paperclip serve --channels paperclip` | `af workforce run` (SSE stream) | Direct execution replaces the channel bridge |",
      "| `af paperclip connect` | — | Not needed — workforces are already reachable at `/v1/workspaces/.../workforce/.../run` |",
      "",
      "## Environment & ID translation",
      "",
      "- Paperclip requires `PAPERCLIP_URL` and `PAPERCLIP_COMPANY_ID` env vars.",
      "- Workforces use the standard `AGENTICFLOW_API_KEY` + `AGENTICFLOW_WORKSPACE_ID` already in `af whoami`. No extra env.",
      "",
      "## Typical migration flow (side-by-side)",
      "",
      "Before (Paperclip):",
      "```bash",
      "af paperclip init --blueprint amazon-seller --paperclip-url http://localhost:3100",
      "af gateway serve --channels paperclip &",
      "af paperclip connect",
      "af paperclip issue list",
      "```",
      "",
      "After (native):",
      "```bash",
      "af workforce init --blueprint amazon-seller --json     # creates wf + PUTs schema",
      "# returns { workforce_id, next_steps: ['af workforce run ...', ...] }",
      "af workforce run --workforce-id <id> --trigger-data '{\"goal\":\"Launch new ASIN\"}'",
      "af workforce publish --workforce-id <id>               # public URL for embed",
      "```",
      "",
      "## What survives unchanged",
      "",
      "- `af agent *`, `af workflow *`, `af connections *`, `af mcp-clients *`, `af knowledge *` —",
      "  these are AgenticFlow-native already and have no Paperclip coupling.",
      "- `af company export/import/diff` — platform-neutral agent bundle I/O.",
      "- `af bootstrap --json` — still returns the full workspace snapshot.",
      "",
      "## Silencing warnings",
      "",
      "```bash",
      "AF_SILENCE_DEPRECATIONS=1 af paperclip blueprints",
      "```",
      "",
      "Use while actively migrating — not as a long-term suppression. The deprecation",
      "removal in 2026-10 will ignore the env var.",
    ].join("\n"),
  },

  "mcp-client-quirks": {
    topic: "mcp-client-quirks",
    title: "MCP Client Quirks — Pipedream vs Composio",
    summary:
      "Not all MCP clients behave the same. This playbook explains a known Pipedream 2-phase failure mode that breaks parametric write tools, and the Composio alternative that works reliably.",
    content: [
      "## Summary",
      "",
      "MCP clients in your workspace fall into two broad families:",
      "- **Pipedream-wrapped** (tool names like `google_sheets-add-single-row`)",
      "- **Composio-wrapped** (tool names like `GOOGLESHEETS_SPREADSHEETS_VALUES_APPEND`)",
      "",
      "The two families expose tool schemas very differently. Pipedream clients often",
      "break on parametric write operations; Composio clients do not. For agents that",
      "need to write rows, create documents, update cells, etc., PREFER Composio.",
      "",
      "## How to tell them apart",
      "",
      "```bash",
      "af mcp-clients get --client-id <id> --json",
      "```",
      "",
      "Inspect the `tools[*].inputSchema`:",
      "- If EVERY tool has exactly one property called `instruction` (type: string),",
      "  you are looking at a Pipedream-wrapped client.",
      "- If tools have structured schemas with multiple named properties",
      "  (e.g. `spreadsheetId`, `range`, `values`), you are looking at a Composio-wrapped",
      "  client.",
      "",
      "## The Pipedream 2-phase problem",
      "",
      "Pipedream tools use a configure → execute handshake under the hood. For most",
      "read-only and one-shot create operations (e.g. `new-spreadsheet`), the single",
      "`instruction` arg carries both phases and the tool works.",
      "",
      "For parametric write operations (e.g. `add-single-row`, `update-row`), the",
      "underlying tool is often exposed through the MCP server as the CONFIGURE step",
      "only — the name `configure_props_<tool>_props` leaks in the error message:",
      "",
      "```",
      "TOOL_CONFIGURATION_COMPLETED",
      "... configure_props_google_sheets-add-single-row_props ...",
      "'I can help add a row to a Google Sheet. What is the ID or name of the Google",
      "Sheet you would like to use?'",
      "```",
      "",
      "The agent is stuck in a config loop: it can 'select the sheet' but never",
      "'write the row'. No prompt instruction will bridge the gap.",
      "",
      "## Workaround: use Composio",
      "",
      "Composio MCP clients expose tools with proper structured schemas. The same",
      "Google Sheets use case works end to end:",
      "",
      "```",
      "allowed tools:",
      "  + GOOGLESHEETS_CREATE_GOOGLE_SHEET1",
      "  + GOOGLESHEETS_SPREADSHEETS_VALUES_APPEND   <-- writes rows!",
      "  + GOOGLESHEETS_VALUES_UPDATE",
      "  + GOOGLESHEETS_UPSERT_ROWS",
      "  + GOOGLESHEETS_GET_SHEET_NAMES",
      "  + GOOGLESHEETS_VALUES_GET",
      "```",
      "",
      "## Detecting the auth mismatch",
      "",
      "`mcp-clients list` can return `is_authenticated: true` for rows that are in",
      "fact unauthenticated (provider token expired / OAuth redirect not completed).",
      "To reconcile, use:",
      "",
      "```bash",
      "af mcp-clients list --verify-auth --json",
      "```",
      "",
      "This calls `get` per row and flags mismatches in `verified_auth_mismatch`.",
      "",
      "## When the CLI attaches an MCP client to an agent",
      "",
      "`af agent update` inspects the MCP client's tool schemas before the PUT.",
      "If it detects write-capable Pipedream tools, it prints a single stderr warning",
      "pointing back to this playbook. Silence with `AF_SILENCE_DEPRECATIONS=1` or",
      "`AF_SILENCE_WARNINGS=1`.",
      "",
      "## Related commands",
      "",
      "- `af mcp-clients list --verify-auth --json` — auth reconcile",
      "- `af mcp-clients get --id <id> --json` — inspect tool schemas (supports --id alias)",
      "- `af agent update --agent-id <id> --patch --body '{...}'` — attach tools without",
      "  round-tripping the full agent object",
    ].join("\n"),
  },

  "marketplace-vs-blueprint": {
    topic: "marketplace-vs-blueprint",
    title: "Blueprint vs Marketplace — When to Use Which",
    summary: "Two ways to start from a template: CLI-shipped blueprints (offline, versioned) or the live marketplace catalog (user/admin curated). This playbook shows when each fits.",
    content: [
      "## Quick decision",
      "",
      "| If you want… | Use |",
      "|---|---|",
      "| A known-good starter that works in any workspace, offline-deployable | **Blueprint** — `af agent init --blueprint <id>` (Tier 1) or `af workforce init --blueprint <id>` (Tier 3) |",
      "| To browse the full AgenticFlow community catalog of agents, workflows, and workforces | **Marketplace** — `af marketplace list --type <kind> --json` |",
      "| A specific user-published template you found via the web UI | **Marketplace** — `af marketplace try --id <item_id>` |",
      "",
      "## What each one IS",
      "",
      "**Blueprints** ship with the CLI (hardcoded in `company-blueprints.ts`, version-locked to the CLI release):",
      "- Tier 1: single agent pre-wired with AgenticFlow-native plugins. No connections. No MAS feature required.",
      "- Tier 3: multi-agent workforce DAG. Requires MAS Workforce feature in the workspace.",
      "- Fixed set, maintained by the AgenticFlow CLI team.",
      "- `af bootstrap --json > blueprints[]` surfaces them with `tier` + `deploy_command`.",
      "",
      "**Marketplace** is the live backend catalog at `/v1/marketplace/items`:",
      "- Unified over three template kinds: `agent_template`, `workflow_template`, `mas_template`.",
      "- User- and admin-curated — updated independently of the CLI.",
      "- Pageable, searchable, filterable by type / featured / free.",
      "- Each item carries embedded `*_template_detail` so a clone needs one GET + one POST.",
      "",
      "## Commands",
      "",
      "```bash",
      "# Blueprints",
      "af bootstrap --json                                 # see all blueprints (tier + deploy_command)",
      "af agent init --blueprint research-assistant --json # Tier 1 deploy (single agent + 4 native plugins)",
      "af workforce init --blueprint dev-shop --json       # Tier 3 deploy (coordinator + N workers)",
      "",
      "# Marketplace",
      "af marketplace list --limit 50 --json                           # browse everything",
      "af marketplace list --type agent_template --search 'seo' --json # filter by kind + keyword",
      "af marketplace list --type mas_template --json                  # only MAS workforce templates",
      "af marketplace get --id <item_id> --json                        # full detail + embedded template",
      "af marketplace try --id <item_id> --dry-run --json              # preview clone payload",
      "af marketplace try --id <item_id> --json                        # actually clone into your workspace",
      "",
      "# Alternate clone paths (same end state)",
      "af templates duplicate agent --template-id <agent_template_id> --json",
      "af templates duplicate workflow --template-id <workflow_template_id> --json",
      "af templates duplicate workforce --template-id <marketplace_item_id> --json",
      "```",
      "",
      "## Cross-workspace caveat (MAS templates only)",
      "",
      "MAS templates reference the SOURCE workspace's agent_ids on their agent nodes. When you clone",
      "a `mas_template`, those ids are unlikely to exist in YOUR workspace — running the duplicated",
      "workforce will 400 on the missing agents.",
      "",
      "`af marketplace try` and `af templates duplicate workforce` both emit a warning listing the",
      "referenced agent_ids so you can duplicate the source agents first. For agent_template /",
      "workflow_template clones the referenced tool workflows are materialized automatically.",
      "",
      "## When blueprints win",
      "",
      "- You're scripting from CI — no network round-trip to marketplace API.",
      "- You want a guaranteed-working starting point that tracks the CLI version.",
      "- The workspace doesn't have MAS Workforce (Tier 1 is the only path that works).",
      "- You want to regenerate identical setup across workspaces without hunting for item ids.",
      "",
      "## When marketplace wins",
      "",
      "- You need something the CLI team didn't ship (custom agents, domain-specific workflows).",
      "- You want user-contributed updates without waiting for a CLI release.",
      "- You're exploring — browsing the catalog is faster than reading 8 blueprint descriptions.",
      "- You're cloning a template a colleague recommended by item id.",
      "",
      "## Related playbooks",
      "",
      "- `af playbook template-bootstrap` — the older `templates sync` + `templates duplicate` flow.",
      "- `af playbook workforce-build` — building a workforce from scratch (no template).",
      "- `af playbook migrate-from-paperclip` — paperclip → workforce command map.",
    ].join("\n"),
  },

  "composition-ladder": {
    topic: "composition-ladder",
    title: "Composition Ladder — Workflow → Agent → Workforce",
    summary: "AgenticFlow's three primitives form a complexity ladder. Start at the lowest rung that solves the user's problem.",
    content: [
      "## The ladder (bottom = simplest)",
      "",
      "| Rung | Kind | Deploy | Description |",
      "| --- | --- | --- | --- |",
      "| 0 | workflow | `af workflow init --blueprint llm-hello` | trigger → llm → output |",
      "| 1 | workflow | `af workflow init --blueprint llm-chain` | llm_plan → llm_execute |",
      "| 2 | workflow | `af workflow init --blueprint summarize-url` | web_retrieval → llm |",
      "| 2 | workflow | `af workflow init --blueprint api-summary` | api_call → llm |",
      "| 3 | agent | `af agent init --blueprint research-assistant` | single agent + plugins |",
      "| 4 | agent | (roadmap) | agent + workflow as tool |",
      "| 5 | agent | (roadmap) | agent + sub-agents |",
      "| 6 | workforce | `af workforce init --blueprint parallel-research` | multi-agent DAG |",
      "",
      "## How they compose",
      "",
      "Each higher rung can reference the rungs below:",
      "- **Workflow** = deterministic chain of nodes (rungs 0-2). No agent, no model autonomy.",
      "- **Agent** = single LLM-driven orchestrator. Uses NODES as plugins (rung 3) or WORKFLOWS as tools (rung 4) or AGENTS as sub-agents (rung 5).",
      "- **Workforce** = explicit DAG of agents + nodes + workflows + sub-DAGs (rung 6).",
      "",
      "## Decision rule (for AI operators)",
      "",
      "Pick the LOWEST rung that solves the user's problem:",
      "",
      "1. **Deterministic, same input → same steps?** → workflow (rungs 0-2).",
      "2. **Needs tool-picking flexibility (LLM decides which tool each turn)?** → agent (rung 3+).",
      "3. **Multiple specialists that must coordinate with explicit parallelism or handoffs?** → workforce (rung 6).",
      "",
      "Common anti-patterns:",
      "- Using a workforce for a single-agent task (over-engineered, harder to debug).",
      "- Using an agent when a workflow would produce identical results deterministically (wastes LLM tokens).",
      "- Using a workflow when the user wants open-ended tool use (agent fits better).",
      "",
      "## Connection requirements",
      "",
      "- **Workflow blueprints** — need one LLM-provider connection (straico/openai/anthropic/etc.) in the workspace. `af workflow init` auto-discovers the first one it finds.",
      "- **Agent blueprints** — need NO connections (use built-in AgenticFlow models via `agenticflow/gpt-4o-mini` etc.).",
      "- **Workforce blueprints** — need NO connections for the 5 batteries-included ones (research-pair, content-duo, api-pipeline, fact-check-loop, parallel-research). The 8 vertical teams (dev-shop, marketing-agency, etc.) need MCP clients attached post-deploy.",
      "",
      "## Browse all blueprints by rung",
      "",
      "```bash",
      "af blueprints list --kind workflow --json       # rungs 0-2",
      "af blueprints list --kind agent --json          # rung 3 (+ 4-5 roadmap)",
      "af blueprints list --kind workforce --json      # rung 6",
      "af blueprints list --complexity 2 --json        # only rung 2",
      "af blueprints get --id summarize-url --json     # full blueprint details",
      "```",
      "",
      "## Related",
      "",
      "- `af playbook ready-prompts` — copy-paste prompts for each rung.",
      "- `af playbook marketplace-vs-blueprint` — live catalog vs CLI-shipped blueprints.",
    ].join("\n"),
  },

  "n8n-to-agenticflow": {
    topic: "n8n-to-agenticflow",
    title: "Convert n8n Workflows to AgenticFlow",
    summary: "Step-by-step blueprint for converting n8n workflows into AgenticFlow workflows — node mapping, expression syntax, input schema, and deployment rules.",
    content: [
      "## Overview",
      "",
      "n8n and AgenticFlow are both workflow automation platforms, but they differ fundamentally:",
      "",
      "| Concept | n8n | AgenticFlow |",
      "|---|---|---|",
      "| Flow control | Explicit connection graph (A → B → C) | Data-flow references (`{{node.field}}` in `input_config`) |",
      "| Node types | 400+ integrations with credentials | ~150 node types; AI-first, connection per category |",
      "| Triggers | Trigger nodes (webhook, schedule, etc.) | `input_schema` defines workflow inputs |",
      "| Branching | `if` / `switch` nodes | No native branching — use `llm` to route or split workflows |",
      "| Expressions | `{{ $json.field }}` / `{{ $('NodeName').item.json.field }}` | `{{node_name.output_field}}` |",
      "| Credentials | Per-node credential objects | Workspace-level App Connections by category |",
      "",
      "## Step 1 — Pre-filter (identify convertible workflows)",
      "",
      "Not every n8n workflow can be converted 1-to-1. Pre-screen using the node mapping below.",
      "A workflow is convertible when ALL its non-sticky nodes have an AgenticFlow equivalent.",
      "",
      "Unsupported n8n patterns:",
      "- Database triggers (real-time change-data-capture): `postgres trigger`, `mysql trigger`",
      "- Binary file pipelines that depend on n8n's in-memory item stream",
      "- Complex `splitInBatches` loops with state carried across iterations",
      "- Sub-workflow outputs referenced mid-loop",
      "",
      "## Step 2 — Map node types",
      "",
      "### Node Selection Priority",
      "",
      "Always pick the highest available tier. Only fall back to a lower tier when the higher tier cannot satisfy the requirement.",
      "",
      "| Tier | Connection required | Examples | When to use |",
      "|---|---|---|---|",
      "| **Tier 1 — AgenticFlow built-in** | None | `llm`, `api_call`, `agenticflow_generate_image`, `send_email`, `web_scraping`, `web_search`, `run_javascript`, `json_to_google_sheet`, `url_to_markdown`, `web_retrieval`, `echo`, `variable_set`, `get_current_datetime`, `drive_get_item_by_path` | Always preferred — no credentials needed |",
      "| **Tier 2 — PixelML** | `pixelml` | `pml_llm`, `generate_image`, `run_python`, `text_to_speech`, `google_search`, `text_extract`, `render_video`, `describe_image` | Use when Tier 1 can't do the job (e.g. Python execution, TTS, image description) |",
      "| **Tier 3 — Vendor-specific** | `openai`, `google_gen_ai`, `telegram`, `tavily`, `firecrawl`, `groq`, `replicate`, `fal`, etc. | `openai_ask_chat_gpt`, `google_gen_ai_ask_gemini`, `telegram_send_message`, `tavily_search`, `firecrawl_scrape` | Last resort — only when a specific vendor API or feature is mandatory |",
      "",
      "**Decision rule for LLM nodes**: use `llm` (Tier 1, model `agenticflow/glm-4.5-air`) by default.",
      "Switch to `pml_llm` (Tier 2) only if PixelML-specific features are required.",
      "Switch to `openai_ask_chat_gpt` / `google_gen_ai_ask_gemini` (Tier 3) only if the workflow explicitly requires GPT-4 / Gemini and cannot be rewritten.",
      "",
      "**Decision rule for image generation**: use `agenticflow_generate_image` (Tier 1) by default.",
      "Fall back to `generate_image` (Tier 2, pixelml connection) if Tier 1 lacks the specific capability.",
      "Only use `openai_generate_image` (Tier 3) when the workflow explicitly requires DALL-E and neither Tier 1 nor Tier 2 can satisfy it.",
      "",
      "### AI / LLM nodes",
      "All text-generation nodes map to `llm` (Tier 1) unless a specific model is mandatory.",
      "Always use `model: \"agenticflow/glm-4.5-air\"` unless the workflow requires a specific model.",
      "",
      "| n8n node type | AgenticFlow node type | Tier |",
      "|---|---|---|",
      "| `@n8n/n8n-nodes-langchain.lmChatOpenAi` | `llm` | 1 |",
      "| `@n8n/n8n-nodes-langchain.lmChatAnthropic` | `llm` | 1 |",
      "| `@n8n/n8n-nodes-langchain.lmChatGoogleGemini` | `llm` | 1 |",
      "| `@n8n/n8n-nodes-langchain.lmChatGroq` | `llm` | 1 |",
      "| `@n8n/n8n-nodes-langchain.lmChatOpenRouter` | `llm` | 1 |",
      "| `@n8n/n8n-nodes-langchain.lmChatDeepSeek` | `llm` | 1 |",
      "| `@n8n/n8n-nodes-langchain.chainLlm` | `llm` | 1 |",
      "| `@n8n/n8n-nodes-langchain.agent` | `llm` | 1 |",
      "| `n8n-nodes-base.openAi` (text ops) | `llm` | 1 |",
      "| `@n8n/n8n-nodes-langchain.informationExtractor` | `llm` (structured output via system prompt) | 1 |",
      "| `@n8n/n8n-nodes-langchain.outputParserStructured` | `llm` (structured output via system prompt) | 1 |",
      "| `@n8n/n8n-nodes-langchain.textClassifier` | `llm` | 1 |",
      "| `n8n-nodes-base.summarize` | `llm` | 1 |",
      "",
      "### Image generation",
      "| n8n node type | AgenticFlow node type | Tier | Notes |",
      "|---|---|---|---|",
      "| `n8n-nodes-base.openAi` (image resource) | `agenticflow_generate_image` | 1 | Preferred |",
      "| `@n8n/n8n-nodes-langchain.openAi` (image resource) | `agenticflow_generate_image` | 1 | Preferred |",
      "| any image gen node (if T1 insufficient) | `generate_image` [pixelml conn] | 2 | Fallback |",
      "| any image gen node (DALL-E explicitly required) | `openai_generate_image` [openai conn] | 3 | Last resort |",
      "",
      "### HTTP & APIs",
      "| n8n node type | AgenticFlow node type | Tier |",
      "|---|---|---|",
      "| `n8n-nodes-base.httpRequest` | `api_call` | 1 |",
      "| `n8n-nodes-base.slack` | `api_call` | 1 |",
      "| `n8n-nodes-base.notion` | `api_call` | 1 |",
      "| `n8n-nodes-base.airtable` | `api_call` | 1 |",
      "| `n8n-nodes-base.hubspot` | `api_call` | 1 |",
      "| `n8n-nodes-base.discord` | `api_call` | 1 |",
      "| `n8n-nodes-base.shopify` | `api_call` | 1 |",
      "| `n8n-nodes-base.stripe` | `api_call` | 1 |",
      "| `n8n-nodes-base.github` | `api_call` | 1 |",
      "| `n8n-nodes-base.jira` | `api_call` | 1 |",
      "| `n8n-nodes-base.wordpress` | `api_call` | 1 |",
      "",
      "### Messaging",
      "| n8n node type | AgenticFlow node type | Tier |",
      "|---|---|---|",
      "| `n8n-nodes-base.telegram` | `telegram_send_message` [telegram conn] | 3 |",
      "| `n8n-nodes-base.telegramTrigger` | `telegram_send_message` [telegram conn] (trigger becomes `input_schema`) | 3 |",
      "| `n8n-nodes-base.emailSend` | `send_email` | 1 |",
      "| `n8n-nodes-base.gmail` | `send_email` | 1 |",
      "| `n8n-nodes-base.gmailTrigger` | `send_email` (trigger becomes `input_schema`) | 1 |",
      "| `n8n-nodes-base.sendGrid` | `send_email` | 1 |",
      "",
      "### Google",
      "| n8n node type | AgenticFlow node type | Tier |",
      "|---|---|---|",
      "| `n8n-nodes-base.googleSheets` | `json_to_google_sheet` | 1 |",
      "| `n8n-nodes-base.googleDrive` | `drive_get_item_by_path` | 1 |",
      "| `n8n-nodes-base.googleDocs` | `api_call` | 1 |",
      "| `n8n-nodes-base.googleCalendar` | `api_call` | 1 |",
      "| `n8n-nodes-base.googleSearch` | `google_search` [pixelml conn] | 2 |",
      "",
      "### Code & data",
      "| n8n node type | AgenticFlow node type | Tier |",
      "|---|---|---|",
      "| `n8n-nodes-base.code` | `run_javascript` | 1 |",
      "| `n8n-nodes-base.function` | `run_javascript` | 1 |",
      "| `n8n-nodes-base.executeCommand` | `run_python` [pixelml conn] | 2 |",
      "| `n8n-nodes-base.spreadsheetFile` | `export_data_to_file` | 1 |",
      "| `n8n-nodes-base.extractFromFile` | `text_extract` [pixelml conn] | 2 |",
      "",
      "### Triggers → `input_schema`",
      "All trigger nodes are removed. Their data fields become `input_schema` properties.",
      "| n8n trigger | `input_schema` fields to define |",
      "|---|---|",
      "| `manualTrigger` | none required |",
      "| `webhook` | `body` (object), or individual fields from expected payload |",
      "| `telegramTrigger` | `message_text` (string), `chat_id` (string) |",
      "| `gmailTrigger` | `email_from`, `email_subject`, `email_body` |",
      "| `scheduleTrigger` | no input needed — run via cron or external scheduler |",
      "| `formTrigger` | one field per form input |",
      "| `chatTrigger` | `user_message` (string) |",
      "",
      "### Control flow → skip or restructure",
      "| n8n node | Strategy |",
      "|---|---|",
      "| `if` / `switch` | Use `llm` with routing instruction, or split into separate workflows |",
      "| `merge` / `aggregate` | Use `run_javascript` to combine data in a prior node |",
      "| `splitOut` / `limit` | Use `run_javascript` to filter/slice arrays |",
      "| `wait` | Remove — AgenticFlow nodes execute sequentially without pauses |",
      "| `noOp` / `stopAndError` | Remove |",
      "",
      "## Step 3 — Convert expressions",
      "",
      "n8n uses JavaScript template expressions. AgenticFlow uses simple `{{node.field}}` references.",
      "",
      "| n8n expression | AgenticFlow equivalent |",
      "|---|---|",
      "| `{{ $json.message.text }}` | `{{message_text}}` (from input_schema) |",
      "| `{{ $('NodeName').item.json.output }}` | `{{node_name.output_field}}` |",
      "| `{{ $json.url }}` | `{{prev_node.url}}` or workflow input `{{url}}` |",
      "| String concat: `\"Hello \" + $json.name` | `\"Hello {{name}}\"` |",
      "",
      "Expression rules:",
      "- Node names must be **snake_case** and unique within the workflow",
      "- References follow the format `{{node_name.output_field_name}}`",
      "- Workflow input fields are referenced directly: `{{field_name}}`",
      "- No JavaScript logic inside references — move logic to a `run_javascript` or `llm` node",
      "",
      "## Step 4 — Build the workflow JSON",
      "",
      "Required top-level fields: `name`, `project_id`, `nodes`, `output_mapping`, `input_schema`, `public_runnable`.",
      "",
      "```json",
      "{",
      "  \"name\": \"My Converted Workflow\",",
      "  \"description\": \"Brief description\",",
      "  \"project_id\": \"YOUR_PROJECT_ID\",",
      "  \"public_runnable\": false,",
      "  \"public_clone\": false,",
      "  \"input_schema\": {",
      "    \"type\": \"object\",",
      "    \"title\": \"Input\",",
      "    \"properties\": {",
      "      \"user_input\": {",
      "        \"type\": \"string\",",
      "        \"title\": \"User Input\",",
      "        \"description\": \"The main input text\",",
      "        \"ui_metadata\": { \"type\": \"short_text\" }",
      "      }",
      "    },",
      "    \"required\": [\"user_input\"]",
      "  },",
      "  \"nodes\": [",
      "    {",
      "      \"name\": \"generate_response\",",
      "      \"title\": \"Generate Response\",",
      "      \"node_type_name\": \"llm\",",
      "      \"input_config\": {",
      "        \"model\": \"agenticflow/glm-4.5-air\",",
      "        \"human_message\": \"{{user_input}}\",",
      "        \"system_message\": \"You are a helpful assistant.\",",
      "        \"chat_history_id\": null,",
      "        \"temperature\": null",
      "      }",
      "    }",
      "  ],",
      "  \"output_mapping\": {",
      "    \"response\": \"{{generate_response.content}}\"",
      "  }",
      "}",
      "```",
      "",
      "## Step 5 — Node `input_config` rules",
      "",
      "1. **Always include ALL fields** defined in the node type's input schema — even unused optional ones.",
      "2. **Unused optional fields must be `null`** — never `\"\"` (empty string) and never omitted.",
      "3. **All `input_schema` properties must have `ui_metadata: { \"type\": \"short_text\" }`** unless the field is a long textarea (use `\"type\": \"long_text\"` in that case).",
      "4. **Node `name` must be snake_case** and unique within the workflow. No spaces or special chars.",
      "5. **Execution order is implicit** — nodes execute top-to-bottom in the `nodes` array. The data-flow references (`{{node.field}}`) determine which values are available.",
      "",
      "### `llm` node — full `input_config` template",
      "```json",
      "{",
      "  \"model\": \"agenticflow/glm-4.5-air\",",
      "  \"human_message\": \"{{input}}\",",
      "  \"system_message\": \"You are a helpful assistant.\",",
      "  \"chat_history_id\": null,",
      "  \"temperature\": null",
      "}",
      "```",
      "",
      "### `api_call` node — full `input_config` template",
      "```json",
      "{",
      "  \"url\": \"https://api.example.com/endpoint\",",
      "  \"method\": \"POST\",",
      "  \"headers\": { \"Content-Type\": \"application/json\" },",
      "  \"body_type\": \"json\",",
      "  \"body\": \"{\\\"key\\\": \\\"{{value}}\\\"}\",",
      "  \"raw_body\": null,",
      "  \"files\": null,",
      "  \"timeout\": null,",
      "  \"response_type\": null,",
      "  \"upload_response\": null",
      "}",
      "```",
      "",
      "### `send_email` node — full `input_config` template",
      "```json",
      "{",
      "  \"recipient_emails\": [\"{{recipient}}\"],",
      "  \"cc_emails\": null,",
      "  \"bcc_emails\": null,",
      "  \"subject\": \"Subject line\",",
      "  \"body\": \"Plain text body\",",
      "  \"body_html\": null",
      "}",
      "```",
      "",
      "### `telegram_send_message` node — full `input_config` template",
      "```json",
      "{",
      "  \"chat_id\": \"{{chat_id}}\",",
      "  \"text\": \"{{message}}\",",
      "  \"business_connection_id\": null,",
      "  \"message_thread_id\": null,",
      "  \"parse_mode\": null,",
      "  \"entities\": null,",
      "  \"link_preview_options\": null,",
      "  \"disable_notification\": null,",
      "  \"protect_content\": null,",
      "  \"allow_paid_broadcast\": null,",
      "  \"message_effect_id\": null,",
      "  \"reply_parameters\": null,",
      "  \"reply_markup\": null",
      "}",
      "```",
      "",
      "### `json_to_google_sheet` node — full `input_config` template",
      "```json",
      "{",
      "  \"title\": \"Sheet Title\",",
      "  \"data\": \"[{\\\"col1\\\": \\\"{{val1}}\\\", \\\"col2\\\": \\\"{{val2}}\\\"}]\",",
      "  \"share_with\": null,",
      "  \"role\": null,",
      "  \"prem_type\": null",
      "}",
      "```",
      "",
      "## Step 6 — Node output fields reference",
      "",
      "| Node type | Output fields |",
      "|---|---|",
      "| `llm` | `content`, `chat_history_id` |",
      "| `pml_llm` | `content`, `chat_history_id` |",
      "| `openai_ask_chat_gpt` | `content` |",
      "| `google_gen_ai_ask_gemini` | `content` |",
      "| `api_call` | `status_code`, `response_body`, `response_url`, `response_headers` |",
      "| `send_email` | `message`, `email_id` |",
      "| `telegram_send_message` | `sent_message`, `success`, `error` |",
      "| `json_to_google_sheet` | `sheet_url`, `sheet_id` |",
      "| `openai_generate_image` | `created`, `data` |",
      "| `web_scraping` | `scraped_content` |",
      "| `google_search` | `search_results` |",
      "| `tavily_search` | `query`, `answer`, `results`, `follow_up_questions` |",
      "| `run_python` | `success`, `stdout`, `stderr` |",
      "| `openai_extract_structured_data` | `data` |",
      "| `drive_get_item_by_path` | `id`, `name`, `download_url`, `path` |",
      "",
      "## Step 7 — Create required connections",
      "",
      "Only Tier 2 (pixelml) and Tier 3 (vendor-specific) nodes require a connection.",
      "Tier 1 nodes (`llm`, `api_call`, `send_email`, `agenticflow_generate_image`, etc.) need NO connection.",
      "",
      "Connection credentials are sensitive. **Do not paste raw API keys into the terminal or share them in plain text.**",
      "Use one of the two options below:",
      "",
      "### Option A — Web UI (recommended)",
      "1. Go to AgenticFlow → Settings → App Connections",
      "2. Click **New Connection**",
      "3. Select the category, enter the connection name (must match the `\"connection\"` field in your workflow JSON), paste the credential value",
      "4. Repeat for each unique connection your workflow needs",
      "",
      "### Option B — Let an AI assistant create connections on your behalf",
      "If working with an AI assistant (Claude, GPT, etc.), tell it:",
      "> \"I need a [category] connection named [name]. Here are my credentials: [values]. Please create it using the CLI.\"",
      "The assistant will run the `agenticflow connections create` command for you.",
      "Credentials are used only to issue the command and are not stored beyond the session.",
      "",
      "### Credential keys by category",
      "| Category | Node types | Credential field |",
      "|---|---|---|",
      "| `pixelml` | `pml_llm`, `generate_image`, `run_python`, `text_to_speech`, `google_search`, `text_extract`, `render_video`, `describe_image` | `api_key` |",
      "| `telegram` | `telegram_send_message` | `bot_token` |",
      "| `openai` | `openai_ask_chat_gpt`, `openai_generate_image` | `api_key` |",
      "| `google_gen_ai` | `google_gen_ai_ask_gemini` | `api_key` |",
      "| `tavily` | `tavily_search` | `api_key` |",
      "| `firecrawl` | `firecrawl_scrape` | `api_key` |",
      "| `groq` | `groq_chat` | `api_key` |",
      "",
      "Once created, the connection name must match the `\"connection\"` field on the node exactly:",
      "```json",
      "{ \"name\": \"send_reply\", \"node_type_name\": \"telegram_send_message\", \"connection\": \"My Telegram\", \"input_config\": { ... } }",
      "```",
      "",
      "## Step 8 — Validate and deploy",
      "",
      "```bash",
      "# 1. Validate locally (no API call)",
      "agenticflow workflow validate --body @workflow.json --local-only",
      "",
      "# 2. Dry-run (calls API, no side effects)",
      "agenticflow workflow create --body @workflow.json --dry-run --json",
      "",
      "# 3. Deploy",
      "agenticflow workflow create --body @workflow.json --json",
      "",
      "# 4. Test",
      "agenticflow workflow run --workflow-id <id> --input @input.json",
      "",
      "# 5. Poll until complete",
      "agenticflow workflow run-status --workflow-run-id <run_id> --json",
      "```",
      "",
      "## Common gotchas",
      "",
      "| Issue | Fix |",
      "|---|---|",
      "| Node name has spaces or capitals | Rename to snake_case (e.g. `send_reply`) |",
      "| `project_id` missing | Required on create — get from `af doctor --json` |",
      "| `public_runnable` missing on update | Required — set to `false` if not publishing publicly |",
      "| Reference `{{NodeName.output}}` not found | Node names are case-sensitive snake_case |",
      "| Empty string `\"\"` in `input_config` | Replace with `null` for all unused optional fields |",
      "| n8n branching (`if`/`switch`) | Route with `llm` instruction, or split into 2 separate workflows |",
      "| n8n loop (`splitInBatches`) | Rewrite as `run_javascript` or `run_python` that processes array |",
      "| Node requires connection | Add an App Connection via `agenticflow connections create --workspace-id <id> --body @conn.json` |",
      "",
      "## Connections required per node type",
      "",
      "Sorted by tier — always pick the lowest-tier option that satisfies the requirement.",
      "",
      "| Tier | Node type | Connection category |",
      "|---|---|---|",
      "| 1 | `llm`, `agenticflow_generate_image`, `api_call`, `send_email`, `json_to_google_sheet`, `run_javascript`, `web_scraping`, `web_search`, `web_retrieval`, `url_to_markdown`, `echo`, `variable_set`, `variable_get`, `get_current_datetime`, `drive_get_item_by_path` | None |",
      "| 2 | `pml_llm`, `generate_image`, `run_python`, `text_to_speech`, `google_search`, `text_extract`, `render_video`, `describe_image` | `pixelml` |",
      "| 3 | `openai_ask_chat_gpt`, `openai_generate_image` | `openai` |",
      "| 3 | `google_gen_ai_ask_gemini` | `google_gen_ai` |",
      "| 3 | `telegram_send_message` | `telegram` |",
      "| 3 | `groq_chat` | `groq` |",
      "| 3 | `tavily_search` | `tavily` |",
      "| 3 | `firecrawl_scrape` | `firecrawl` |",
      "| 3 | `replicate_run_model` | `replicate` |",
      "| 3 | `fal_run_model` | `fal` |",
      "",
      "Create a connection:",
      "```bash",
      "agenticflow connections create --workspace-id <workspace_id> --body '{",
      "  \"name\": \"My OpenAI\",",
      "  \"category\": \"openai\",",
      "  \"workspace_id\": \"<workspace_id>\",",
      "  \"project_id\": \"<project_id>\",",
      "  \"value\": { \"api_key\": \"sk-...\" }",
      "}' --json",
      "```",
      "Then pass the connection name in the node: `\"connection\": \"My OpenAI\"`.",
    ].join("\n"),
  },

  "ready-prompts": {
    topic: "ready-prompts",
    title: "Copy-Paste User Prompts — Hand These to an AI",
    summary: "Pre-written prompts a user can paste into any AI chat to trigger the right deploy flow. Each prompt is deliberately minimal — the AI is expected to use `af bootstrap --json` + `af blueprints list --json` to discover and pick the right option.",
    content: [
      "## How to use",
      "",
      "Give ONE of the prompts below to any AI assistant (Claude Code, Cursor, ChatGPT with shell access, etc.) that has the `af` CLI available. The AI will discover the surface on its own and deploy the right thing. The prompts are deliberately light — they describe the goal, not the command.",
      "",
      "The CLI is designed so `af bootstrap --json` + `af blueprints list --json` + `af marketplace list` cover every decision an AI needs. Don't over-specify.",
      "",
      "## 🧭 \"I don't know what this does\" (first-time user)",
      "",
      "```",
      "I have an AgenticFlow workspace set up. I want to understand what this platform actually does. Using the `af` CLI,",
      "pick a simple ready-made starter that gives me a tangible sense of what AgenticFlow can do, deploy it, test it with",
      "a realistic prompt, and report what you saw. Clean up after. Prefer something that works in any workspace without",
      "needing extra features enabled.",
      "```",
      "",
      "## 🔎 Research agent (single agent, web-grounded)",
      "",
      "```",
      "Set up a research agent for me that can answer current-events questions with cited sources from the web. Use the",
      "`af` CLI. Test it with a real recent-news question. When the response comes back, confirm it actually used web",
      "search (not just training data). Clean up after.",
      "```",
      "",
      "## ✍️  Content + image pipeline (2 agents)",
      "",
      "```",
      "Help me deploy a small content workforce: one agent drafts written content, another generates a matching image.",
      "Use the `af` CLI. Test it by having it produce a short blog-post-style piece on a topic of your choice — show me",
      "both the written output and confirm the image generation step ran. Clean up after.",
      "```",
      "",
      "## 🧩 Fan-out research (4 agents, parallel investigation)",
      "",
      "```",
      "I want to see a multi-agent workforce that investigates a question in parallel. Deploy a fan-out research",
      "workforce via the `af` CLI and test it with a 'compare X vs Y' question. Confirm both researcher agents ran",
      "in parallel and a synthesizer produced the final unified answer. Clean up after.",
      "```",
      "",
      "## 🔗 API + analyst (HTTP data pipeline)",
      "",
      "```",
      "Deploy an HTTP API pipeline workforce using the `af` CLI. Pick a realistic public API to test with (jsonplaceholder,",
      "GitHub API, weather API, etc.) and a question that requires fetching + analyzing the response. Verify the first",
      "agent actually made an HTTP call and the second agent produced a user-facing answer grounded in the response.",
      "Clean up after.",
      "```",
      "",
      "## ✅ Fact-checked draft (writer + fact-checker)",
      "",
      "```",
      "Deploy a fact-check-loop workforce via `af`. Give it a topic with specific factual claims (e.g. a recent company",
      "announcement, a statistic in the news, an upcoming event). Confirm the writer drafted something AND the fact-checker",
      "actually verified claims against the live web. Clean up after.",
      "```",
      "",
      "## 🛍️ Browse the live marketplace",
      "",
      "```",
      "Using the `af marketplace` commands, browse the live template catalog. Pick an item that looks genuinely useful",
      "(not a test entry), clone it into my workspace, verify it works end-to-end with a realistic prompt, then clean",
      "up. Tell me what you picked and why.",
      "```",
      "",
      "## 🏢 Domain team (pick a vertical blueprint)",
      "",
      "```",
      "I run a [YOUR BUSINESS — e.g. 'small marketing agency' or 'tutoring business' or 'freelance consulting practice'].",
      "Using `af bootstrap` and `af blueprints list`, find the blueprint that matches, deploy it, and run one realistic",
      "starter task. Summarize what got created and how to run the team day-to-day.",
      "```",
      "",
      "## 🧪 What the AI is expected to do with these",
      "",
      "1. Run `af bootstrap --json` — gets auth, commands cheat sheet, 16 blueprints with `tier` + `deploy_command`.",
      "2. Run `af blueprints list --json` (or filter `--tier 1|3`) to see offline-deployable options.",
      "3. Run `af marketplace list --json` only if blueprints don't fit.",
      "4. Execute the chosen deploy with `--dry-run --json` first, then live.",
      "5. Smoke-test with a realistic prompt that exercises the agents' plugins.",
      "6. Delete every resource it created.",
      "",
      "If your AI skips steps or picks the wrong tier (Tier 3 when workspace doesn't have MAS Workforce feature), surface",
      "that as feedback — `bootstrap --json > whats_new.for_ai` is the routing rulebook and should prevent wrong picks.",
    ].join("\n"),
  },
};

export function listPlaybooks(): Playbook[] {
  return Object.keys(PLAYBOOKS)
    .sort()
    .map((key) => PLAYBOOKS[key]);
}

export function getPlaybook(topic: string): Playbook | null {
  return PLAYBOOKS[topic] ?? null;
}
