/**
 * CLI playbooks derived from AgenticFlow skill references.
 */

export interface Playbook {
  topic: string;
  title: string;
  summary: string;
  content: string;
}

export const PLAYBOOKS: Record<string, Playbook> = {
  "first-touch": {
    topic: "first-touch",
    title: "First Touch For New Agents",
    summary: "Zero-context onboarding path from install to first successful workflow, agent, and template bootstrap runs.",
    content: [
      "Start here (no prior context required)",
      "1. Verify CLI is available:",
      "   `agenticflow --help`",
      "2. Verify auth + connectivity:",
      "   `agenticflow whoami --json`",
      "   `agenticflow doctor --json --strict`",
      "3. Discover command surface:",
      "   `agenticflow discover --json`",
      "   `agenticflow playbook --list`",
      "   `agenticflow workflow --help`",
      "   `agenticflow agent --help`",
      "   `agenticflow ops list --public-only --json`",
      "4. Seed local template context (recommended for cold agents):",
      "   `agenticflow templates sync --limit 100 --json`",
      "   `agenticflow templates index --json`",
      "5. Discover build primitives:",
      "   `agenticflow node-types search --query <task> --json`",
      "   `agenticflow node-types get --name <node_type> --json`",
      "   `agenticflow connections list --limit 200 --json`",
      "6. Validate and run workflow lifecycle:",
      "   `agenticflow workflow validate --body @workflow.json --local-only`",
      "   `agenticflow workflow validate --body @workflow.json`",
      "   `agenticflow workflow create --body @workflow.json`",
      "   `agenticflow workflow run --workflow-id <id> --input @input.json --json`",
      "   `agenticflow workflow run-status --workflow-run-id <run_id> --json`",
      "7. Create and run agent lifecycle:",
      "   `agenticflow agent create --body @agent.json`",
      "   `agenticflow agent get --agent-id <id> --json`",
      "   `agenticflow agent update --agent-id <id> --body @agent-update.json`",
      "   `agenticflow agent stream --agent-id <id> --body @stream.json`",
      "",
      "Error contract for automation",
      "- With `--json`, command failures return:",
      "  `{ \"schema\": \"agenticflow.error.v1\", \"code\": \"...\", \"message\": \"...\", \"hint\": \"optional\" }`",
      "- Local payload checks fail with `local_schema_validation_failed` before network calls.",
      "- Handle `operation_not_found` by using suggestions or running:",
      "  `agenticflow ops list --public-only --json`",
      "- Handle `invalid_option_value` by validating numeric flags (`--limit`, `--offset`, `--top`).",
      "",
      "Operational defaults",
      "- Always use `--json` in agent automation.",
      "- Always use `doctor --strict` at startup.",
      "- Prime templates locally via `templates sync` before creating net-new assets.",
      "- Prefer `node-types search/get` over huge `list` payloads.",
      "- Use `call --dry-run --json` before unknown low-level calls.",
      "- If local templates are insufficient, continue with:",
      "  `https://docs.agenticflow.ai/`",
      "  `https://docs.agenticflow.ai/~gitbook/mcp`",
    ].join("\n"),
  },
  "template-bootstrap": {
    topic: "template-bootstrap",
    title: "Bootstrap From Templates",
    summary: "Fetch template samples locally so cold agents can compose workflows, agents, and workforces with less trial-and-error.",
    content: [
      "Template bootstrap flow",
      "1. Sync templates into local cache:",
      "   `agenticflow templates sync --limit 100 --json`",
      "2. Inspect local cache summary:",
      "   `agenticflow templates index --json`",
      "3. Read generated files in `.agenticflow/templates`:",
      "   - `manifest.json` (counts, source operations, sync issues)",
      "   - `workflow_templates.json`, `agent_templates.json`, `workforce_templates.json`",
      "   - `workflow/`, `agent/`, `workforce/` per-template files",
      "4. Duplicate templates directly (web-like flow):",
      "   `agenticflow templates duplicate workflow --template-id <workflow_template_id> --json`",
      "   `agenticflow templates duplicate agent --template-id <agent_template_id> --json`",
      "   `agenticflow templates duplicate agent --template-file <local_agent_template.json> --cache-dir .agenticflow/templates --dry-run --json`",
      "5. Build custom assets by adapting nearest templates, then validate:",
      "   `agenticflow workflow validate --body @workflow.json --local-only`",
      "   `agenticflow agent create --body @agent.json`",
      "6. If templates do not cover your use case, continue with docs:",
      "   `https://docs.agenticflow.ai/`",
      "   `https://docs.agenticflow.ai/~gitbook/mcp`",
      "",
      "Notes",
      "- `workforce` template source may require `--workforce-id <id>` on some backends.",
      "- `templates duplicate agent` duplicates referenced workflow templates first.",
      "- Use `--cache-dir .agenticflow/templates` to resolve workflow templates locally before API fetch.",
      "- Use `--strict` during sync when CI must fail on partial fetch.",
    ].join("\n"),
  },
  "workflow-build": {
    topic: "workflow-build",
    title: "Build Workflows",
    summary: "Design a linear node pipeline and publish it with CLI commands.",
    content: [
      "Workflow design checklist",
      "1. Define `input_schema` first.",
      "2. Discover node types: `agenticflow node-types list` or `agenticflow node-types search --query llm`.",
      "3. Inspect node requirements: `agenticflow node-types get --name <node_type>`.",
      "4. Fetch dynamic dropdown values when needed:",
      "   `agenticflow node-types dynamic-options --name <node_type> --field-name <field>`.",
      "5. Create workflow JSON body with required fields:",
      "   `name`, `project_id`, `nodes`, `output_mapping`, `input_schema`.",
      "6. Create workflow:",
      "   `agenticflow workflow create --workspace-id <workspace_id> --body @workflow.json`.",
      "7. Update workflow:",
      "   `agenticflow workflow update --workspace-id <workspace_id> --workflow-id <workflow_id> --body @workflow.json`.",
      "",
      "Notes",
      "- Prefer node types that do not require connections when possible.",
      "- Workflows execute sequentially top-to-bottom.",
      "- Use `{{...}}` references to map outputs from prior nodes.",
    ].join("\n"),
  },
  "workflow-run": {
    topic: "workflow-run",
    title: "Run Workflows",
    summary: "Execute a workflow and monitor the workflow run lifecycle.",
    content: [
      "Run checklist",
      "1. Start run:",
      "   `agenticflow workflow run --workflow-id <workflow_id> --input @input.json`.",
      "2. Poll status:",
      "   `agenticflow workflow run-status --workflow-run-id <workflow_run_id>`.",
      "3. Inspect result fields:",
      "   `status`, `output`, `state.nodes_state`, `state.error`.",
      "",
      "Tips",
      "- Keep polling until status is `success` or `failed`.",
      "- Validate workflow payloads before create/update:",
      "  `agenticflow workflow validate --body @workflow.json`.",
    ].join("\n"),
  },
  "agent-build": {
    topic: "agent-build",
    title: "Build Agents",
    summary: "Create and operate agents with tool configs and stream calls.",
    content: [
      "Agent checklist",
      "1. Prepare create payload with required fields:",
      "   `name`, `tools`, `project_id`.",
      "2. Create agent:",
      "   `agenticflow agent create --body @agent.json`.",
      "3. Read/update agent:",
      "   `agenticflow agent get --agent-id <agent_id>`",
      "   `agenticflow agent update --agent-id <agent_id> --body @agent-update.json`.",
      "4. Interact through streaming endpoint:",
      "   `agenticflow agent stream --agent-id <agent_id> --body @stream-body.json`.",
      "",
      "Best practices",
      "- Keep tool sets minimal and focused.",
      "- Use explicit system prompts and response formats.",
      "- Test with short stream prompts before production traffic.",
    ].join("\n"),
  },
  "mcp-to-cli-map": {
    topic: "mcp-to-cli-map",
    title: "MCP To CLI Mapping",
    summary: "Replace common AgenticFlow MCP actions with native CLI commands.",
    content: [
      "MCP style -> CLI equivalent",
      "- `agenticflow_list_node_types` -> `agenticflow node-types list`",
      "- `agenticflow_search_node_types` -> `agenticflow node-types search --query <q>`",
      "- `agenticflow_get_node_type_details` -> `agenticflow node-types get --name <node_type>`",
      "- `agenticflow_get_dynamic_options` ->",
      "  `agenticflow node-types dynamic-options --name <node_type> --field-name <field>`",
      "- `agenticflow_create_workflow` ->",
      "  `agenticflow workflow create --workspace-id <workspace_id> --body @workflow.json`",
      "- `agenticflow_update_workflow` ->",
      "  `agenticflow workflow update --workspace-id <workspace_id> --workflow-id <workflow_id> --body @workflow.json`",
      "- `agenticflow_execute_workflow` ->",
      "  `agenticflow workflow run --workflow-id <workflow_id> --input @input.json`",
      "- `agenticflow_get_workflow_run` ->",
      "  `agenticflow workflow run-status --workflow-run-id <workflow_run_id>`",
      "- `agenticflow_list_app_connections` ->",
      "  `agenticflow connections list --workspace-id <workspace_id>`",
    ].join("\n"),
  },
};

export function listPlaybooks(): Playbook[] {
  return Object.keys(PLAYBOOKS)
    .sort()
    .map((key) => PLAYBOOKS[key]);
}

export function getPlaybook(topic: string): Playbook | null {
  return PLAYBOOKS[topic] ?? null;
}
