/**
 * CLI playbooks derived from AgenticFlow skill references.
 */

export interface Playbook {
  topic: string;
  title: string;
  summary: string;
  content: string;
}

export const PLAYBOOKS: Record<string, Playbook> = {
  "first-touch": {
    topic: "first-touch",
    title: "First Touch For New Agents",
    summary: "Zero-context onboarding path from install to first successful workflow, agent, and template bootstrap runs.",
    content: [
      "Start here (no prior context required)",
      "1. Verify CLI is available:",
      "   `agenticflow --help`",
      "2. Verify auth + connectivity:",
      "   `agenticflow whoami --json`",
      "   `agenticflow doctor --json --strict`",
      "3. Discover command surface:",
      "   `agenticflow discover --json`",
      "   `agenticflow playbook --list`",
      "   `agenticflow workflow --help`",
      "   `agenticflow agent --help`",
      "   `agenticflow ops list --public-only --json`",
      "4. Seed local template context (recommended for cold agents):",
      "   `agenticflow templates sync --limit 100 --json`",
      "   `agenticflow templates index --json`",
      "5. Discover build primitives:",
      "   `agenticflow node-types search --query <task> --json`",
      "   `agenticflow node-types get --name <node_type> --json`",
      "   `agenticflow connections list --limit 200 --json`",
      "6. Validate and run workflow lifecycle:",
      "   `agenticflow workflow validate --body @workflow.json --local-only`",
      "   `agenticflow workflow validate --body @workflow.json`",
      "   `agenticflow workflow create --body @workflow.json`",
      "   `agenticflow workflow run --workflow-id <id> --input @input.json --json`",
      "   `agenticflow workflow run-status --workflow-run-id <run_id> --json`",
      "7. Create and run agent lifecycle:",
      "   `agenticflow agent create --body @agent.json`",
      "   `agenticflow agent get --agent-id <id> --json`",
      "   `agenticflow agent update --agent-id <id> --body @agent-update.json`",
      "   `agenticflow agent stream --agent-id <id> --body @stream.json`",
      "",
      "Error contract for automation",
      "- With `--json`, command failures return:",
      "  `{ \"schema\": \"agenticflow.error.v1\", \"code\": \"...\", \"message\": \"...\", \"hint\": \"optional\" }`",
      "- Local payload checks fail with `local_schema_validation_failed` before network calls.",
      "- Handle `operation_not_found` by using suggestions or running:",
      "  `agenticflow ops list --public-only --json`",
      "- Handle `invalid_option_value` by validating numeric flags (`--limit`, `--offset`, `--top`).",
      "",
      "Operational defaults",
      "- Always use `--json` in agent automation.",
      "- Always use `doctor --strict` at startup.",
      "- Prime templates locally via `templates sync` before creating net-new assets.",
      "- Prefer `node-types search/get` over huge `list` payloads.",
      "- Use `call --dry-run --json` before unknown low-level calls.",
      "- If local templates are insufficient, continue with:",
      "  `https://docs.agenticflow.ai/`",
      "  `https://docs.agenticflow.ai/~gitbook/mcp`",
    ].join("\n"),
  },
  "template-bootstrap": {
    topic: "template-bootstrap",
    title: "Bootstrap From Templates",
    summary: "Fetch template samples locally so cold agents can compose workflows, agents, and workforces with less trial-and-error.",
    content: [
      "Template bootstrap flow",
      "1. Sync templates into local cache:",
      "   `agenticflow templates sync --limit 100 --json`",
      "2. Inspect local cache summary:",
      "   `agenticflow templates index --json`",
      "3. Read generated files in `.agenticflow/templates`:",
      "   - `manifest.json` (counts, source operations, sync issues)",
      "   - `workflow_templates.json`, `agent_templates.json`, `workforce_templates.json`",
      "   - `workflow/`, `agent/`, `workforce/` per-template files",
      "4. Duplicate templates directly (web-like flow):",
      "   `agenticflow templates duplicate workflow --template-id <workflow_template_id> --json`",
      "   `agenticflow templates duplicate agent --template-id <agent_template_id> --json`",
      "   `agenticflow templates duplicate agent --template-file <local_agent_template.json> --cache-dir .agenticflow/templates --dry-run --json`",
      "5. Build custom assets by adapting nearest templates, then validate:",
      "   `agenticflow workflow validate --body @workflow.json --local-only`",
      "   `agenticflow agent create --body @agent.json`",
      "6. If templates do not cover your use case, continue with docs:",
      "   `https://docs.agenticflow.ai/`",
      "   `https://docs.agenticflow.ai/~gitbook/mcp`",
      "",
      "Notes",
      "- `workforce` template source may require `--workforce-id <id>` on some backends.",
      "- `templates duplicate agent` duplicates referenced workflow templates first.",
      "- Use `--cache-dir .agenticflow/templates` to resolve workflow templates locally before API fetch.",
      "- Use `--strict` during sync when CI must fail on partial fetch.",
    ].join("\n"),
  },
  "workflow-build": {
    topic: "workflow-build",
    title: "Build Workflows",
    summary: "Design a linear node pipeline and publish it with CLI commands.",
    content: [
      "Workflow design checklist",
      "1. Define `input_schema` first.",
      "2. Discover node types: `agenticflow node-types list` or `agenticflow node-types search --query llm`.",
      "3. Inspect node requirements: `agenticflow node-types get --name <node_type>`.",
      "4. Fetch dynamic dropdown values when needed:",
      "   `agenticflow node-types dynamic-options --name <node_type> --field-name <field>`.",
      "5. Create workflow JSON body with required fields:",
      "   `name`, `project_id`, `nodes`, `output_mapping`, `input_schema`.",
      "6. Create workflow:",
      "   `agenticflow workflow create --workspace-id <workspace_id> --body @workflow.json`.",
      "7. Update workflow:",
      "   `agenticflow workflow update --workspace-id <workspace_id> --workflow-id <workflow_id> --body @workflow.json`.",
      "",
      "Notes",
      "- Prefer node types that do not require connections when possible.",
      "- Workflows execute sequentially top-to-bottom.",
      "- Use `{{...}}` references to map outputs from prior nodes.",
    ].join("\n"),
  },
  "workflow-run": {
    topic: "workflow-run",
    title: "Run Workflows",
    summary: "Execute a workflow and monitor the workflow run lifecycle.",
    content: [
      "Run checklist",
      "1. Start run:",
      "   `agenticflow workflow run --workflow-id <workflow_id> --input @input.json`.",
      "2. Poll status:",
      "   `agenticflow workflow run-status --workflow-run-id <workflow_run_id>`.",
      "3. Inspect result fields:",
      "   `status`, `output`, `state.nodes_state`, `state.error`.",
      "",
      "Tips",
      "- Keep polling until status is `success` or `failed`.",
      "- Validate workflow payloads before create/update:",
      "  `agenticflow workflow validate --body @workflow.json`.",
    ].join("\n"),
  },
  "agent-build": {
    topic: "agent-build",
    title: "Build Agents",
    summary: "Create and operate agents with tool configs and stream calls.",
    content: [
      "Agent checklist",
      "1. Prepare create payload with required fields:",
      "   `name`, `tools`, `project_id`.",
      "2. Create agent:",
      "   `agenticflow agent create --body @agent.json`.",
      "3. Read/update agent:",
      "   `agenticflow agent get --agent-id <agent_id>`",
      "   `agenticflow agent update --agent-id <agent_id> --body @agent-update.json`.",
      "4. Interact through streaming endpoint:",
      "   `agenticflow agent stream --agent-id <agent_id> --body @stream-body.json`.",
      "",
      "Best practices",
      "- Keep tool sets minimal and focused.",
      "- Use explicit system prompts and response formats.",
      "- Test with short stream prompts before production traffic.",
    ].join("\n"),
  },
  "quickstart": {
    topic: "quickstart",
    title: "Quickstart: Zero to Working Agent in 5 Minutes",
    summary: "Complete onboarding path for new AgenticFlow users. Install, authenticate, create your first agent, and send it a task.",
    content: [
      "## Step 1: Install",
      "```",
      "npm install -g @pixelml/agenticflow-cli",
      "```",
      "Verify: `af --help` (af is the short alias for agenticflow)",
      "",
      "## Step 2: Authenticate",
      "```",
      "af login",
      "```",
      "This saves your API key, workspace ID, and project ID to ~/.agenticflow/auth.json",
      "",
      "Verify auth + connectivity:",
      "```",
      "af doctor --json --strict",
      "af whoami --json",
      "```",
      "",
      "## Step 3: Create Your First Agent",
      "```",
      'af agent create --body \'{"name": "My Assistant", "tools": [], "project_id": "YOUR_PROJECT_ID"}\'',
      "```",
      "Note the `id` in the response — this is your agent ID.",
      "",
      "Or list existing agents:",
      "```",
      "af agent list --json",
      "```",
      "",
      "## Step 4: Talk to Your Agent",
      "```",
      'af agent stream --agent-id <AGENT_ID> --body \'{"messages": [{"content": "Hello! What can you do?"}]}\'',
      "```",
      "",
      "## Step 5: Add Tools (Optional)",
      "Build a workflow tool for your agent:",
      "```",
      "af node-types search --query llm --json",
      "af workflow create --body @my-workflow.json",
      "af agent update --agent-id <AGENT_ID> --body @add-tools.json",
      "```",
      "",
      "## What Next?",
      "- `af playbook agent-build` — deep dive into agent configuration",
      "- `af playbook gateway-setup` — receive tasks from Paperclip, Linear, or any webhook",
      "- `af playbook deploy-to-paperclip` — deploy agents to a Paperclip company",
      "- `af playbook template-bootstrap` — start from pre-built templates",
      "",
      "## For AI Agents Reading This",
      "1. Always use `--json` flag for machine-readable output.",
      "2. Run `af doctor --json --strict` at startup to verify connectivity.",
      "3. Use `af discover --json` to learn the full command surface.",
      "4. Use `af playbook --list` to find relevant guides for your task.",
      "5. Errors follow `{ schema: 'agenticflow.error.v1', code, message, hint }` format.",
    ].join("\n"),
  },
  "gateway-setup": {
    topic: "gateway-setup",
    title: "Gateway: Receive Tasks From Any Platform",
    summary: "Set up the webhook gateway to receive tasks from Paperclip, Linear, GitHub, or any custom webhook and route them to AgenticFlow agents.",
    content: [
      "The gateway is a webhook server that translates external platform events",
      "into AgenticFlow agent calls. It supports multiple channels simultaneously.",
      "",
      "## Concept: Channels",
      "A channel is any platform that sends tasks to your agents:",
      "- **paperclip** — Paperclip heartbeat webhooks (task management for AI companies)",
      "- **linear** — Linear issue/comment webhooks (engineering project management)",
      "- **webhook** — Generic JSON POST (any system, any automation)",
      "",
      "List available channels:",
      "```",
      "af gateway channels",
      "```",
      "",
      "## Quick Start: Generic Webhook (No Setup Required)",
      "```",
      "af gateway serve --channels webhook --verbose",
      "```",
      "Now send a task from anywhere:",
      "```",
      "curl -X POST http://localhost:4100/webhook/webhook \\",
      '  -H "Content-Type: application/json" \\',
      '  -d \'{"agent_id": "<AF_AGENT_ID>", "message": "Summarize the Q4 report"}\'',
      "```",
      "The agent processes the task and returns the result in the HTTP response.",
      "",
      "With a callback URL, results are also POSTed back:",
      "```",
      "curl -X POST http://localhost:4100/webhook/webhook \\",
      '  -H "Content-Type: application/json" \\',
      '  -d \'{"agent_id": "<ID>", "message": "Do X", "callback_url": "https://your-app.com/results"}\'',
      "```",
      "",
      "## Paperclip Channel",
      "Receive tasks from a Paperclip company:",
      "```",
      "af gateway serve --channels paperclip --paperclip-url http://localhost:3100 --verbose",
      "```",
      "Then configure Paperclip agents with `adapterConfig.url = http://localhost:4100/webhook/paperclip`.",
      "Or use the shortcut: `af paperclip connect` (updates all deployed agents).",
      "",
      "Full Paperclip workflow: see `af playbook deploy-to-paperclip`.",
      "",
      "## Linear Channel",
      "Receive tasks from Linear issues:",
      "```",
      "export LINEAR_API_KEY=lin_api_xxxxx",
      'export LINEAR_AGENT_MAP=\'{"ENG": "<af-agent-id>", "DES": "<af-agent-id>"}\'',
      "af gateway serve --channels linear --verbose",
      "```",
      "Then in Linear: Settings > API > Webhooks > add URL:",
      "  `https://your-gateway-url/webhook/linear`",
      "  Events: Issues (created, updated), Comments (created)",
      "",
      "The gateway maps Linear teams to AF agents via LINEAR_AGENT_MAP.",
      "When an issue is created in team ENG, the mapped agent processes it.",
      "Agent responses are posted back as Linear comments.",
      "",
      "## Multiple Channels Simultaneously",
      "```",
      "af gateway serve --channels paperclip,linear,webhook --verbose",
      "```",
      "Each channel gets its own webhook endpoint:",
      "- POST /webhook/paperclip",
      "- POST /webhook/linear",
      "- POST /webhook/webhook",
      "- GET /health (lists active channels)",
      "",
      "## Serverless Deployment",
      "The gateway exports a standard Request -> Response handler.",
      "Import `createGatewayHandler` from the SDK for Vercel, Lambda, etc:",
      "```typescript",
      "import { createGatewayHandler } from '@pixelml/agenticflow-cli/gateway/server';",
      "import { WebhookConnector } from '@pixelml/agenticflow-cli/gateway/connectors';",
      "const handler = createGatewayHandler(config, [new WebhookConnector()]);",
      "export default handler; // Vercel / Cloudflare Workers",
      "```",
      "No always-running server required.",
      "",
      "## For AI Agents Reading This",
      "1. Start with `af gateway serve --channels webhook` for the simplest setup.",
      "2. Use `af gateway channels` to see available connectors.",
      "3. The generic webhook accepts: `{ agent_id, message, task_id?, callback_url? }`.",
      "4. Health check: `GET /health` returns `{ connectors: [...] }`.",
      "5. To add a new channel, implement the ChannelConnector interface.",
    ].join("\n"),
  },
  "deploy-to-paperclip": {
    topic: "deploy-to-paperclip",
    title: "Deploy Agents to Paperclip",
    summary: "Publish AgenticFlow agents to a Paperclip company where they receive tasks, execute work, and report results — all from the CLI.",
    content: [
      "Paperclip is an orchestration control plane for AI agent companies.",
      "AgenticFlow agents can be deployed to Paperclip as HTTP-adapter workers",
      "that receive tasks and execute them.",
      "",
      "## Prerequisites",
      "- AgenticFlow CLI authenticated (`af login` or `af doctor`)",
      "- At least one agent in AgenticFlow (`af agent list`)",
      "- A running Paperclip instance (default: http://localhost:3100)",
      "",
      "## Step 1: Create a Company",
      "```",
      'af paperclip company create --name "My AI Company" --budget 100000',
      "```",
      "Budget is in cents (100000 = $1,000/month).",
      "",
      "## Step 2: Deploy Agents",
      "Deploy an AgenticFlow agent to Paperclip:",
      "```",
      "af paperclip deploy --agent-id <AF_AGENT_ID> --role engineer",
      "```",
      "Available roles: ceo, cto, cmo, cfo, engineer, designer, pm, qa, devops, researcher, general.",
      "",
      "Deploy multiple agents to build a team:",
      "```",
      "af paperclip deploy --agent-id <ID1> --role engineer",
      "af paperclip deploy --agent-id <ID2> --role cmo",
      "af paperclip deploy --agent-id <ID3> --role designer",
      "```",
      "",
      "## Step 3: Set Goals and Create Tasks",
      "```",
      'af paperclip goal create --title "Launch the product by Q2" --level company --status active',
      "```",
      "```",
      'af paperclip issue create --title "Build landing page" --assignee <PC_AGENT_ID> --priority high',
      "```",
      "",
      "## Step 4: Start the Gateway",
      "```",
      "af gateway serve --channels paperclip --verbose",
      "```",
      "",
      "## Step 5: Connect Agents to the Gateway",
      "```",
      "af paperclip connect",
      "```",
      "This updates all deployed agents to route heartbeats through the gateway.",
      "",
      "## Step 6: Trigger Work",
      "```",
      'af paperclip agent wakeup --id <PC_AGENT_ID> --reason "Work on your tasks"',
      "```",
      "The gateway fetches the agent's assigned issue from Paperclip,",
      "sends the full task context to the AgenticFlow agent, and posts",
      "the agent's response back as a comment on the issue.",
      "",
      "## Step 7: Monitor",
      "```",
      "af paperclip dashboard",
      "af paperclip issue list",
      "af paperclip issue comments --id <ISSUE_ID>",
      "```",
      "",
      "## Full Command Reference",
      "```",
      "af paperclip company list|get|create|update|archive|delete",
      "af paperclip agent list|get|update|pause|resume|terminate|wakeup|delete",
      "af paperclip goal list|get|create|update|delete",
      "af paperclip issue list|get|create|update|assign|comment|comments|delete",
      "af paperclip approval list|approve|reject",
      "af paperclip dashboard",
      "af paperclip deploy --agent-id <id>",
      "af paperclip connect",
      "```",
      "",
      "## Environment Variables",
      "```",
      "PAPERCLIP_URL=http://localhost:3100   # Paperclip instance URL",
      "PAPERCLIP_COMPANY_ID=<uuid>           # Default company (auto-detected if only one)",
      "```",
      "",
      "## For AI Agents Reading This",
      "1. Run `af agent list --json` to find available AgenticFlow agents.",
      "2. Run `af paperclip company create --name <name>` to set up a company.",
      "3. Use `af paperclip deploy --agent-id <id> --role <role>` for each agent.",
      "4. Start the gateway: `af gateway serve --channels paperclip`.",
      "5. Connect agents: `af paperclip connect`.",
      "6. Create goals and issues, then trigger heartbeats.",
      "7. Check results with `af paperclip issue comments --id <id>`.",
      "8. Company ID auto-resolves when only one company exists.",
    ].join("\n"),
  },
  "agent-channels": {
    topic: "agent-channels",
    title: "Connect Agents to External Channels",
    summary: "Route work to AgenticFlow agents from Linear, Paperclip, GitHub, Slack, or any webhook — using the gateway as a universal adapter.",
    content: [
      "AgenticFlow agents can receive work from any platform via the gateway.",
      "This playbook shows how to wire up each supported channel.",
      "",
      "## Architecture",
      "```",
      "External Platform  →  POST /webhook/<channel>  →  Gateway  →  AF Agent  →  Result back to platform",
      "```",
      "",
      "## Channel 1: Generic Webhook (simplest)",
      "Any system that can make HTTP requests can send tasks:",
      "```",
      "af gateway serve --channels webhook",
      "```",
      "Send a task:",
      "```json",
      "{",
      '  "agent_id": "<AF_AGENT_ID>",',
      '  "message": "Analyze this data and provide insights",',
      '  "task_id": "TASK-001",',
      '  "callback_url": "https://my-app.com/webhook/results"',
      "}",
      "```",
      "POST to: `http://gateway:4100/webhook/webhook`",
      "",
      "Use cases: Zapier, Make, n8n, custom apps, cron jobs, Slack bots, CI/CD.",
      "",
      "## Channel 2: Paperclip",
      "Full AI company orchestration with goals, tasks, budgets:",
      "```",
      "af gateway serve --channels paperclip --paperclip-url http://localhost:3100",
      "af paperclip deploy --agent-id <id>",
      "af paperclip connect",
      "```",
      "See `af playbook deploy-to-paperclip` for the full guide.",
      "",
      "## Channel 3: Linear",
      "Engineering project management — agents process Linear issues:",
      "```",
      "export LINEAR_API_KEY=lin_api_xxxxx",
      'export LINEAR_AGENT_MAP=\'{"ENG": "<af-agent-id>", "DESIGN": "<af-agent-id>"}\'',
      "af gateway serve --channels linear",
      "```",
      "In Linear: Settings > API > Webhooks > add `https://your-url/webhook/linear`",
      "",
      "How it works:",
      "- Issue created in ENG team → mapped AF agent receives full issue context",
      "- Comment added to issue → agent processes the comment",
      "- Agent response posted back as a Linear comment",
      "",
      "## Running Multiple Channels",
      "```",
      "af gateway serve --channels paperclip,linear,webhook --verbose",
      "```",
      "Each channel gets its own endpoint. One gateway handles all platforms.",
      "",
      "## Adding a New Channel",
      "Implement the ChannelConnector interface (2 methods):",
      "```typescript",
      "interface ChannelConnector {",
      "  name: string;",
      "  parseWebhook(headers, body): Promise<NormalizedTask | null>;",
      "  postResult(task, resultText): Promise<void>;",
      "}",
      "```",
      "parseWebhook: extract task info from the platform's webhook payload.",
      "postResult: post the agent's response back to the platform.",
      "",
      "## For AI Agents Reading This",
      "1. The simplest channel is `webhook` — just POST `{ agent_id, message }`.",
      "2. For Paperclip: use `af paperclip deploy` + `af paperclip connect`.",
      "3. For Linear: set LINEAR_API_KEY and LINEAR_AGENT_MAP, add webhook in Linear UI.",
      "4. Multiple channels can run simultaneously on one gateway.",
      "5. Health check: `GET /health` shows active channels.",
      "6. All channels normalize to NormalizedTask before calling AF agent.",
    ].join("\n"),
  },
  "mcp-to-cli-map": {
    topic: "mcp-to-cli-map",
    title: "MCP To CLI Mapping",
    summary: "Replace common AgenticFlow MCP actions with native CLI commands.",
    content: [
      "MCP style -> CLI equivalent",
      "- `agenticflow_list_node_types` -> `agenticflow node-types list`",
      "- `agenticflow_search_node_types` -> `agenticflow node-types search --query <q>`",
      "- `agenticflow_get_node_type_details` -> `agenticflow node-types get --name <node_type>`",
      "- `agenticflow_get_dynamic_options` ->",
      "  `agenticflow node-types dynamic-options --name <node_type> --field-name <field>`",
      "- `agenticflow_create_workflow` ->",
      "  `agenticflow workflow create --workspace-id <workspace_id> --body @workflow.json`",
      "- `agenticflow_update_workflow` ->",
      "  `agenticflow workflow update --workspace-id <workspace_id> --workflow-id <workflow_id> --body @workflow.json`",
      "- `agenticflow_execute_workflow` ->",
      "  `agenticflow workflow run --workflow-id <workflow_id> --input @input.json`",
      "- `agenticflow_get_workflow_run` ->",
      "  `agenticflow workflow run-status --workflow-run-id <workflow_run_id>`",
      "- `agenticflow_list_app_connections` ->",
      "  `agenticflow connections list --workspace-id <workspace_id>`",
    ].join("\n"),
  },
};

export function listPlaybooks(): Playbook[] {
  return Object.keys(PLAYBOOKS)
    .sort()
    .map((key) => PLAYBOOKS[key]);
}

export function getPlaybook(topic: string): Playbook | null {
  return PLAYBOOKS[topic] ?? null;
}
